### ISSUE TITLE
Crear mid SGA

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#1]
Crear el nuevo mid para sistema de gestión académica.
- [x] El nuevo sistema esta en go
- [x] El nuevo sistema integra el modulo de produccion academica.
- [x] El nuevo sistema integra el modulo de eventos.
- [ ] El nuevo sistema integra el modulo de habilitación de periodo.

**Comment by JuanPiedrahita** [comment]
Para correr el api el archivo custom.env debe existir y debe contener valores imilares a estos:

PRODUCCION_ACADEMICA_SERVICE=prod_crud:8080/v1
PERSONAS_SERVICE=api.planestic.udistrital.edu.co:8083/v1/
EVENTOS_SERVICE=eventos_crud:8080/v1/
OIKOS_SERVICE=10.20.0.254/oikos_api/v1/
CORE_SERVICE=simulacion:8096/v1/

**Comment by JuanPiedrahita** [comment]
@fabianbarreto02, por favor incluir en el mid el modlo para habilitación de periodo.

**Comment by fabianbarreto02** [comment]
Se realiza la integracion del controlador para consulta oferta academica, queda pendiente el merge entre la rama creada y dev
