### ISSUE TITLE
Mid para consultar los registros del proyecto con la información de OIKOS (5h)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#10]
Se debe configurar el mid para traer organizado las fechas de los registros por separado, registro calificado y registro de alta calidad, de igual manera traer nombre de la dependencia para poder visualizar en la consulta general del cliente.

Lider técnica : @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se espera Revisión por parte de la lider tecnica @mafeave

**Comment by mafeave** [comment]
Ajustar el servicio para que cuando se solicite información de un proyecto que no existe, devuelva un JSON vacío. 
Se está presentando el siguiente error al hacer la consulta con un proyecto que no existe: 
![image](https://user-images.githubusercontent.com/14035745/65836364-2a1d4f80-e2b6-11e9-922c-1bd60d7693c5.png)

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste definido por la Lider técnica, se espera revisión de nuevo por parte de la Lider

**Comment by mafeave** [comment]
Revisado el ajuste, se da por finalizada la tarea.
