### ISSUE TITLE
Crear controlador en sga_mid para gestión de transacción con solicitud_crud y anidamiento con produccion_academica

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#109]

**Comment by CrissUD** [comment]
# Creación de estructura de controlador solicitud docente

Se crea un nuevo controlador en **sga_mid** el cual es llamado **solicitud_docente** y que apunta a la api crud **solicitud_crud** dicha estructura inicial esta basada en la estructura del controlador **produccion_academica** y no es probada:
![image](https://user-images.githubusercontent.com/44172561/100453548-1ff90b80-3089-11eb-8000-41b8c59d3672.png)
![image](https://user-images.githubusercontent.com/44172561/100453596-37d08f80-3089-11eb-865e-db236f29c6df.png)

**Comment by CrissUD** [comment]
# Creación de método PostSolicitudDocente

Se crea el método para poder enviar una transacción de solicitud docente que va dirigida al api crud **solicitud_crud**, esta transacción abarca las siguientes tablas:
* solicitud
* solicitante
* solicitud_evolucion_estado
* observacion

Se genera entonces la estructura de la información para que pueda ser enviada correctamente al api crud:

![code2](https://user-images.githubusercontent.com/44172561/100453860-bb8a7c00-3089-11eb-851b-8b3f291a8898.png)
Dicho método es probado con Postman y posteriormente desde el cliente **produccion_academica_crud** 

*Nota: Falta crear función para calcular fecha limite en evolución de estado*

**Comment by CrissUD** [comment]
# Creación Método para obtener todas las solicitudes de un tercero

Se crea un método get encargado de obtener todas las solicitudes docentes que haya realizado un tercero, esta trae todas la información de las tablas que como se menciono en el anterior comentario, hacen parte de una transacción de solicitud. Para esto realiza la petición de get al api crud **solicitud_crud**

![code3](https://user-images.githubusercontent.com/44172561/100454136-4ff4de80-308a-11eb-8a66-1d019388d6aa.png)

Dicho método fue probado desde postman y posteriormente en el cliente **produccion_academica_cliente**

**Comment by fabianbarreto02** [comment]
Se revisa y se aprueba el pull en el entrono de pruebas
