### ISSUE TITLE
Revisión subir archivos a Google drive desde go

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#110]

**Comment by EstefaniaPerezTorres** [comment]
Pasos para activar la API Google Drive en la cuenta

Ingresar a la [consola de servicios de google](https://console.developers.google.com/projectselector2/apis/credentials) para activar las credenciales. Para esto se debe crear un proyecto dando clic en el botón que dice **CREAR PROYECTO** como se muestra en la siguiente imagen.

![image](https://user-images.githubusercontent.com/72519041/101171846-5b0db880-360e-11eb-829a-54c91c197c05.png)
 
Ahí solo debe ingresar el nombre de un proyecto y darle clic en **CREAR**. Una vez creado el proyecto, se dirigirá de nuevo a la página de credenciales donde mostrará el listado de **Claves de API**, **IDs de cliente de OAuth 2.0** y las **Cuentas de seervicio**. Para que los token de autenticación no venzan se debe crear una cuenta de servicio nueva ya que si se hace por cliente OAuth 2.0 estas credenciales caducarán.

Para crear la Cuenta de servicio nueva se debe dar clic en el link que dice **Administración de cuentas de servicio** que aparece al costado derecho de esta esta lista. Se dirigirá a la siguiente página:

![image](https://user-images.githubusercontent.com/72519041/101172606-60b7ce00-360f-11eb-8171-2718d48c3d7f.png)

Se debe dar clic en el botón que aparece en la parte superior llamado **CREAR CUENTA DE SERVICIO**. Allí se debe poner el nombre a la cuenta, se da clic en **CREAR** y luego el rol dependiendo lo que se espera realizar con esta cuenta. Para este caso se utilizó el rol de propietario y el paso opcional de _Conceder a los usuarios acceso a esta cuenta de servicio_ se dejo vacía.

![image](https://user-images.githubusercontent.com/72519041/101173408-81ccee80-3610-11eb-978d-f77d57fc1598.png)

![image](https://user-images.githubusercontent.com/72519041/101173456-9315fb00-3610-11eb-987a-ede44dc49784.png)

![image](https://user-images.githubusercontent.com/72519041/101173532-ac1eac00-3610-11eb-939c-15b0e5381442.png)

Dar clic en **LISTO**. Para obtener el Json con las credenciales debemos editar el servicio creado dando clic en los tres puntos y luego en **Editar**

![image](https://user-images.githubusercontent.com/72519041/101174140-775f2480-3611-11eb-96ab-53b14a4b774b.png)

Bajamos a la parte de claves y de damos en **Añadir clave**, luego en **Crear clave** y dejamos seleccionado el formato Json. Se decargará el archivo Json en la carpeta de descargas y este será el que se va a utilizar en el proyecto.

![image](https://user-images.githubusercontent.com/72519041/101174220-9493f300-3611-11eb-92ea-2676e4af26d0.png)

![image](https://user-images.githubusercontent.com/72519041/101174295-affefe00-3611-11eb-8cd4-2d60ebc4dfdb.png)

**Comment by EstefaniaPerezTorres** [comment]
Se deben habilitar las librerias del API con los siguientes comandos
`go get -u google.golang.org/api/drive/v3`
`go get -u golang.org/x/oauth2/google`

Para subir los documentos a Drive se utiliza el siguiente código:

_import que se deben tener:_


`	package main

	import (
		"context"
		"encoding/json"
		"fmt"
		"io"
		"io/ioutil"
		"log"
		"net/http"

		"golang.org/x/oauth2/google"
		"golang.org/x/oauth2/jwt"
		"google.golang.org/api/drive/v3"
	)

	//Método para subir los documentos y crear la capeta correspondiente
	func uploadFile(w http.ResponseWriter, r *http.Request) {
		//Se mostrará cuando se suba el documento a Drive
		fmt.Fprint(w, "Subido documento")
		
		//Obtenemos el input type=file del formulario que tiene por nombre "myFile"
		f, handle, err := r.FormFile("myFile")
		if err != nil {
			fmt.Println("Error 1")
			fmt.Println(err)
			return
		}

		defer f.Close()
		
		// Creamos el cliente con las credenciales del archivo json, este debe estar en la raíz del proyecto
		client := ServiceAccount("client_secret.json")

		srv, err := drive.New(client)
		if err != nil {
			log.Fatalf("Unable to retrieve drive Client %v", err)
		}

		//ID de la carpeta donde se crearán las carpetas de los docentes
		folder := "1snEUvKYFg0Cq6rOhqHW6-KHWsexDs4nf"
		//Nombre para la nueva carpeta por docente
		folderName := "NombreDocente"
		//Inicializar variable que tendrá el ID de la carpeta creada
		folderId := ""

		// Query para obtener la carpeta que corresponde al nombre previo y verificación que se busca en objetos de tipo "folder"
		q := fmt.Sprintf("name=\"%s\" and mimeType=\"application/vnd.google-apps.folder\"", folderName)
		// Obtiene la lista de las carpetas que corresponden al query anterior
		m, err := srv.Files.List().Q(q).Do()
		if err != nil {
			log.Fatalf("Unable to retrieve files: %v", err)
		}

		//En caso que no exista la carpeta se crea y se obtiene su ID, sino se obtiene el ID de la carpeta existente
		if len(m.Files) == 0 {
			//Step 3: Create directory
			dir, err := createFolder(srv, folderName, folder)

			if err != nil {
				panic(fmt.Sprintf("Could not create dir: %v\n", err))
			}

			folderId = dir.Id

		} else {
			for _, i := range m.Files {
				folderId = i.Id
			}
		}

	
		// Creación del archivo pasando por parámetro el servicio, el nombre del archivo, el archivo y el ID de la carpeta donde se va a guardar
		file, err := createFile(srv, handle.Filename, "application/octet-stream", f, folderId)

		if err != nil {
			panic(fmt.Sprintf("Could not create file: %v\n", err))
		}
		fmt.Printf("File '%s' successfully uploaded", file.Id)

		//Se busca el archivo creado y trae con todos los atributos para obtener el link de visualización
		y, err := srv.Files.Get(file.Id).Fields("*").Do()
		if err != nil {
			fmt.Printf("An error occurred: %v\n", err)
		}

		fmt.Printf("Link: '%v' ", y.WebViewLink)
	}

	//Método para definir la ruta donde se correrá el programa
	func setupRoutes() {
		http.HandleFunc("/upload", uploadFile)
		http.ListenAndServe(":8080", nil)
	}

	//Creación del servicio según las credenciales del archivo pasado por parámetro 
	func ServiceAccount(secretFile string) *http.Client {
		b, err := ioutil.ReadFile(secretFile)
		if err != nil {
			log.Fatal("error while reading the credential file", err)
		}
		var s = struct {
			Email      string `json:"client_email"`
			PrivateKey string `json:"private_key"`
		}{}
		json.Unmarshal(b, &s)
		config := &jwt.Config{
			Email:      s.Email,
			PrivateKey: []byte(s.PrivateKey),
			Scopes: []string{
				drive.DriveScope,
			},
			TokenURL: google.JWTTokenURL,
		}
		client := config.Client(context.Background())
		return client
	}	

	//Creación de carpetas
	func createFolder(service *drive.Service, name string, parentId string) (*drive.File, error) {
		d := &drive.File{
			Name:     name,
			MimeType: "application/vnd.google-apps.folder",
			Parents:  []string{parentId},
		}

		file, err := service.Files.Create(d).Do()

		if err != nil {
			log.Println("Could not create dir: " + err.Error())
			return nil, err
		}

		return file, nil
	}

	//Creación de archios
	func createFile(service *drive.Service, name string, mimeType string, content io.Reader, parentId string) (*drive.File, error) {
		f := &drive.File{
			MimeType: mimeType,
			Name:     name,
			Parents:  []string{parentId},
		}
		file, err := service.Files.Create(f).Media(content).Do()

		if err != nil {
			log.Println("Could not create file: " + err.Error())
			return nil, err
		}

		return file, nil
	}

	 //Main
	func main() {
	
		setupRoutes()

	}
`

**Comment by fabianbarreto02** [comment]
Realizar pruebas definidas

**Comment by CrissUD** [comment]
Realizar ajustes de respuesta a controlador

**Comment by CrissUD** [comment]
# Controlador para envió de documentos a Drive y ajustes de respuestas

Una vez realizada la prueba separada de la subida de archivos a Drive, se crea un controlador dentro de la api **sga_mid** el cual estará encargado de realizar la tarea de la subida de archivos a Drive que solicite el cliente **produccion_academica_cliente**: de esta manera el controlador queda con un método principal de la siguiente manera: 
![codeDrive](https://user-images.githubusercontent.com/44172561/101382768-56533980-3886-11eb-8f5d-573d78aa40ca.png)

Además se realiza el refactor correspondiente a los lineamientos de las OAS para el envió de respuesta una vez se complete la petición o esta falle por algún motivo:

![codeDrive1](https://user-images.githubusercontent.com/44172561/101382996-987c7b00-3886-11eb-8485-9e69d2d687dd.png)

**Comment by CrissUD** [comment]
# Generación de Metadato

Una vez el proceso de subida a Drive se complete se agrega un método adicional que esta encargado del registro del metadato en la producción académica registrada por el docente que va a contener el link generado para visualización del archivo en Drive:
![codeDrive2](https://user-images.githubusercontent.com/44172561/101383327-fb6e1200-3886-11eb-9f41-398ee8318de9.png)

**Comment by CrissUD** [comment]
# Realización de pruebas

Se realizan una serie de pruebas con la subida de archivos a Drive para ver los casos específicos que podrían suceder en la ejecución real de la aplicación,  a continuación se explican cada una de las pruebas realizadas:

## Envió de archivo de gran tamaño
* **Descripción de prueba:**
Se realiza una prueba subiendo un archivo en formato de video que pesa 2,37GB. 

* **Resultados:**
Los resultados muestran que la subida del archivo se demoro un total de 1 hora con 12 minutos (01:12:12), la prueba se realiza desde un ambiente local por lo que este tiempo podría disminuirse una vez el sistema este en pruebas o producción.

* **Conclusiones:**
Hasta este punto se tenía como dinámica de subida de archivos a Drive, que el docente debía esperar en la página web hasta que terminara la carga, sin embargo por cuestiones practicas y para evitar errores relacionados con el tiempo de permanencia de un usuario en la página web se opto por cambiar el mecanismo para que un usuario suba la solicitud y el proceso de subida a Drive sea independiente, de esta forma el cliente puede seguir interactuando con la página web mientras se hace el cargue del archivo a Drive internamente. 

## Prueba de concurrencia
* **Descripción de prueba:**
Se realiza el envió de una solicitud que contiene un archivo para subir a Drive que pesa 232 Mb y mientras se esta subiendo el archivo, se generan otras peticiones como consulta de solicitudes, creación de solicitudes etc.
* **Resultados:**
Los resultados muestran que mientras el archivo se esta subiendo a Drive es posible generar otras peticiones al SGA_MID como consulta de modificaciones incluso se creo otra solicitud de tipo de producción académica de articulo completo el cual fue subido satisfactoriamente, después de su debido tiempo el sistema completo la subida del archivo y genero el metadato correspondiente con el link generado.
* **Conclusiones:**
La prueba muestra que el sistema esta preparado para una concurrencia masiva de peticiones donde es posible realizar mas acciones mientras se suben archivos pesados a Drive.

## Prueba de solicitudes con archivos a Drive
* **Descripción de prueba:**
Se realiza una prueba en donde se envía dos solicitudes al mismo tiempo con diferentes roles en donde existen archivos que deben subirse a Drive.
* **Resultados:**
Los resultados muestran que en dicho caso ambas solicitudes quedan registradas y la subida de archivos se realiza de forma independiente y dependiendo del tamaño del archivo se sube primero uno o el otro.
* **Conclusiones:**
Se puede concluir que la subida de archivos se realiza de forma independiente y el tiempo de subida depende del tamaño de cada archivo.

## Prueba de subida de archivos al mismo Drive
* **Descripción de prueba:**
Se realiza una prueba en donde se envía dos archivos al mismo tiempo uno desde el SGA_MID y otro desde una aplicación externa de pruebas.
* **Resultados:**
Los resultados muestran que los archivos se suben al drive sin esperar que el otro suba, mientras en el SGA_MID se estaba subiendo un archivo de 150Mb en la aplicación externa se pudo subir un archivo de 32Mb dos veces
* **Conclusiones:**
Se puede concluir que la subida de archivos desde diferentes appis es independiente y no se genera la espera de la subida de otro archivo.

## Prueba de subida de archivos a Drive y posterior cierre de sesión
* **Descripción de prueba:**
Se realiza la subida de una solicitud en donde se debe agregar un archivo a Drive que pesa 145 Mb y luego del mensaje del registro exitoso de la solicitud se cierra sesión y se espera a ver si esto afecta la subida del archivo a Drive.
* **Resultados:**
Los resultados muestran que aunque el usuario cierre sesión, la subida del archivo a Drive queda enlistada en el SGA_MID y esta se realizará sin mayor problema 
* **Conclusiones:**
Se concluye que un usuario puede realizar diferentes acciones en la página web incluso puede cerrar sesión y el archivo será subido a Drive

## Prueba de subida de archivos a Drive y posterior perdida de internet en el cliente
* **Descripción de prueba:**
Se realizan varias pruebas de la subida de una solicitud en donde se debe agregar un archivo a Drive de diferentes tamaños y luego del mensaje del registro exitoso de la solicitud se quita el internet del cliente.
* **Resultados:**
Los resultados muestran que pueden existir varios casos, para empezar existe un tiempo en el que el cliente pasa el archivo a la api de SGA_MID y luego esta se encarga de subir el archivo a Drive, si el internet del cliente es quitado en el proceso de envío del archivo al SGA_MID este no podrá realizar la petición satisfactoriamente, por otro lado si el archivo ya fue recibido por el SGA_MID el  proceso de subida a Drive se generará satisfactoriamente independiente de que el cliente se haya quedado sin internet
* **Conclusiones:**
Se concluye que existe un tiempo intermedio que representa el envió de información al SGA_MID que es crucial para que funcione la petición correctamente, una vez el archivo es recibido por esta api el proceso se vuelve totalmente independiente y puede realizarse satisfactoriamente. En caso de que la solicitud se haya registrado pero no se paso el archivo para drive al SGA_MID el usuario puede volver a subirlo en el apartado de modificar solicitud.

## Prueba de subida de archivos a Drive y posterior perdida de internet en el SGA_MID
* **Descripción de prueba:**
Se realizan varias pruebas de la subida de una solicitud en donde se debe agregar un archivo a Drive de diferentes tamaños y luego del mensaje del registro exitoso de la solicitud se quita el internet del SGA_MID.
* **Resultados:**
Los resultados muestran que si el api SGA_MID no esta funcionando la subida a Dirve no podrá realizarse y en el cliente saldrá un mensaje indicando el error de la subida.
* **Conclusiones:**
Se concluye que el servicio de la api SGA_MID debe estar en constante funcionamiento, una vez desplegado en los servidores AMAZON se espera que el servicio no falle en ningún momento

**Comment by EstefaniaPerezTorres** [comment]
**Put del archivo subido a Drive**
En caso de modificación del archivo subido a Drive actualiza el link con el correspondiente al nuevo archivo.

![image](https://user-images.githubusercontent.com/72519041/101849805-730d9c80-3b26-11eb-9f07-62e41b661683.png)

**Comment by EstefaniaPerezTorres** [comment]
**Generación de API Google mid**
Se pasa controlador al API de Google_mid y se actualiza cliente para apuntar a esta API.

**Comment by EstefaniaPerezTorres** [comment]
**Carpeta generada para guardar producciones del mes**
Se actualiza nombre de la carpeta generada para que se cree cada mes con el año y el mes respectivos

![image](https://user-images.githubusercontent.com/72519041/101850193-4443f600-3b27-11eb-9cb1-b964c1952cfc.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada esta issue

**Comment by CrissUD** [comment]
Ajustar variables de entorno
