### ISSUE TITLE
Crear función para crear actividad hija de un padre 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#113]
Se debe crear una función que reciba la información de la nueva actividad y el id de la actividad padre, debe crear la nueva actividad, agregar la relación entre las actividades y devolver la actividad creada, la issue debe cumplir con los siguientes requerimientos:

- [x] Debe recibir  la información de la nueva actividad y el id de la actividad padre

- [x] Debe crear la actividad nueva

- [x] Establecer la relación entre las actividad padre/hija 

- [x] Retornar la información de la actividad creada

**Comment by ricardoavendano** [comment]
Debe recibir la información de la nueva actividad y el id de la actividad padre: Recibe información del padre para crear la relación

 Debe crear la actividad nueva: Se crea nuevo registro en la tabla calendario_evento asociando el padre

 Establecer la relación entre las actividad padre/hija: Se crea la relación

 Retornar la información de la actividad creada: Retorna el post con la información de la nueva actividad hija creada

Commit:

https://github.com/udistrital/sga_cliente/pull/273/commits/1db46f998ece5242a7d4d5ca9c71514a5bd6441b
https://github.com/udistrital/sga_cliente/pull/273/commits/81323c24f6e778c1b259c0b469c1ddd36781e4f6
https://github.com/udistrital/sga_cliente/pull/273/commits/ed4fa60512af0480fe0160bcc5e478aa4da84702

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
