### ISSUE TITLE
Revisión del modelo de datos del parametros_estandar para el registro de los derechos pecuniarios

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#118]
Se debe revisar el [modelo](https://github.com/udistrital/parametros_crud/blob/develop/sql/modelo_parametros_crud.png) de parametros_crud en el cual se realizara el registro de los derechos pecuniarios, para esto se debe revisar los [mockups](https://docs.google.com/document/d/1s41Jqd06-I4hfOJR-lWTZ2NoRBnrf_IVaD_6w_4t8TA/edit), para la issue debe cumplir con los siguiente requerimientos:

- [x] Analizar el nuevo modelo y establecer como realizar los registros de los conceptos  y posterior registros del costo a cada concepto 

- [x] Tener en cuenta que cada derecho pecuniario se registra cuando se cambia el salario mínimo

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de la tarea

**Comment by gabrielablanco** [comment]
Una vez se analiza el modelo y el mockup expuesto se resume lo siguiente:

### La tabla *parámetro* almacenará la información de la normativa.
Así se vería en la tabla:
*id*: Número de la circular 
*nombre*: Asunto de la circular
*descripcion*: resumen de la circular
*codigo_abreviacion*: **N/A** 
*activo*: Estado de la circular para un periodo 
*numero_orden*: **N/A**
*fecha_creacion*: Fecha que aparece en la parte superior de la circular
*fecha_modificacion*: Fecha en la que se sube una nueva acta en ese periodo (caso especial)
*tipo_parametro_id*: **N/A**
*parametro_padre_id*: Identificador de una circular padre si llega a existir una modificación en la circular actual

### La tabla *parametro_periodo* almacenará la información de el concepto.
Así se vería en la tabla:
*id*: Identificador del concepto
*parametro_id*: Referencia de la circular relacionada a este concepto
*periodo_id*: Referencia de la vigencia de este concepto
*valor*: JSON de la siguiente estructura
**{
   *factor*
   *salario_minimo*
   *valor*: Operación entre el factor y el salario mínimo
}**
**NOTA: Este campo es obligatorio por lo que solo se puede agregar un concepto si este JSON tiene información** 
*fecha_creacion*: Fecha de la circular donde se especifican los conceptos
*fecha_modificacion*: **N/A**
*activo*: 

### La tabla *periodo* almacenará la información de la vigencia
Así se vería en la tabla:
*id*: Identificador de la vigencia
*nombre*: 
*descripcion*:
*year*: Año que se aplica la vigencia
*ciclo*: **N/A**
*codigo_abreviacion*: **N/A**
*activo*: Estado de la vigencia 
*aplicacion_id*: **N/A**
*inicio_vigencia*: Fecha en la cual inicia a regir la vigencia
*fin_vigencia*: Fecha en la cual finaliza la vigencia
*fecha_creacion*: Fecha en la que se agrega la vigencia
*fecha_modificacion*: Fecha en la que se modifica la vigencia (caso especial)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
