### ISSUE TITLE
Crear función para realizar la creación de un concepto y posterior registro del costo del concepto 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#119]
Se debe crear una función donde se cree el concepto y se cree a su vez el registro a la tabla de rompimiento parametro_periodo y se registre el valor del factor al concepto creado, después de esto se debe crear una función que cree un parámetro hijo donde se relacione y registre el costo del concepto ya antes definido, la issue debe cumplir con los siguiente requerimientos:

- [x] Realizar función  que cree el concepto y realice la relación de la vigencia y el valor del factor 

- [x] Realizar la función que cree el sub parámetros con el concepto para el almacenamiento del costo del concepto antes definido

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta actividad

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
