### ISSUE TITLE
Ajustar función que consulta los calendarios completos para la consulta general del calendario

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#132]
Se debe ajustar la función de consulta de calendario cuando es una consulta general del calendario, pues al crear actividades especificas no se deben mostrar las actividades especificas en una consulta general del calendario, la issue debe cumplir con los siguientes requerimientos: 

- [x] Ajustar o crear una nueva función para la consulta general de un calendario sin actividades hijas 

- [x] Ajustar en el cliente donde se tenga que consultar el calendario general para utilizar la función indicada

**Comment by ricardoavendano** [comment]
Se ajusta desde el cliente la consulta de las actividades por calendario, en el calendario general solo aparecen las actividades padre, en el detalle aparecen tanto las actividades padre e hijas
commit
https://github.com/udistrital/sga_cliente/pull/284/commits/812c5a7a6ba61f0ed511d02ac2cf3896b415302c

Ajuste mid de la funcion que consulta calendarios por proyecto para devolver mas campos necesarios en el cliente
commit
https://github.com/udistrital/sga_mid/pull/145/commits/c58c13855afcd54f80b2e1ab669b4ee31650ec54

**Comment by fabianbarreto02** [comment]
en la consulta general puedo observar las actividades hijas, solo se deberia mirar por la consulta de un proyecto

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue
