### ISSUE TITLE
Revisar y consultar librerias para la generación de los códigos de barras con go con el estándar EAN-128 - 10 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#14]
Se debe revisar las librerias desarrolladas en lenguaje go para la generación de codigo de barras con el estándar EAN-128, para el desarrollo del modulo de inscripción y la generación del PIN de pago.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Durante el proceso de consulta de librerias para la creación de codigos de barras en lenguaje go, se encontraron las siguientes consideraciones:

- El estandar EAN- 128, es un estandar antiguio, nace del estandar code 128, el cual puede representar en su totalidad el codigo ASCII, lo mas relevante del estandar EAN-128 son los identificadores de aplicación, los cuales representan que tipo de información sigue despues del identificador y su longitud.
- Con ayuda de @FaustoPuerto  se revisa el estandar para el código de caudo el cual se puede observar en la siguiente figura:

![Cod_:barras](https://user-images.githubusercontent.com/43799065/67099499-b0c1a000-f183-11e9-8b5c-4cec73b0cac2.png)

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
