### ISSUE TITLE
Función de construcción de PDF para generar los recibos de pago 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#147]
Se debe desarrollar un controlado que reciba un json y realice la construcción del PDF del recibo de pago para el proceso de inscripción, se debe tener en cuenta para la construcción del PDF el [documento](https://docs.google.com/document/d/1BnN321qmiKNztcD3hcBhZnHEQqbfbxxX1Y32GWHr1vY/edit) dado, la issue debe cumplir con los siguientes documentos:
 
- [x] Revisar documentación sobre que librerías en go permite la creación de documentos PDF

- [x] Recibir  el JSON  del cliente con la siguiente información:
`{
"NombreDelAspirante":"nombre_aspirante",
"DocumentoDelAspirante": "documento_aspirante",
"ProyectoAspirante": "proyecto_aspirante",
"Periodo":"periodo",
"Descripcion": "nombre_derecho_pecuniario",
"ValorDerecho":"valor_derecho_pecuniario",
"Fecha_pago": "fecha_actividad_consultada" 
}`

- [x] Construir el archivo PDF con la información recibida del JSON y con el en maquetada definido en documento 

- [x] Revisar como realizar el response a nivel de cliente para observar el recibo, analizar si es posible enviar el pdf en formato binario

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea

**Comment by jupmorenor** [comment]
Se realizó búsqueda de librerías de Go que permitan la construcción de documentos pdf, encontrando las siguientes:

- [unipdf](https://github.com/unidoc/unipdf): es una librería comercial y se requiere adquirir una licencia par poder usarla.
- [gopdf](https://github.com/signintech/gopdf): no está pensada par uso formal.
- [gofpdf](https://github.com/phpdave11/gofpdf): es una transcripción a Go de la librería Fpdf original de php, es la mas avanzada de las librerías disponibles, y aunque el repositorio original ha dejado de recibir mantenimiento, este fork continúa recibiendolo.
- [pdfcpu](https://github.com/pdfcpu/pdfcpu): Aunque esta librería ofrece una API para procesamiento de archivos pdf, en realidad, su principal enfoque es el manejo de consola de comandos.
- [maroto](https://github.com/johnfercher/maroto): Esta librería hace un wrapper de gofpdf agregando facilidades para el manejo del layout al estilo de Bootstrap, sin embargo, su desarrollo no se encuentra muy avanzado.

Después de este análisis se decide usar gofpdf.

**Comment by jupmorenor** [comment]
El resultado de4 usar esta función es un archivo en formato PDF como el que se deja adjunto, sin embargo, para efectos de comunicación entre la API y el cliente, se genera una respuesta que contiene una cadena de texto que corresponde al archivo codificado en formato base64.

[reciboGenerado.pdf](https://github.com/udistrital/sga_mid/files/5704650/reciboGenerado.pdf)

**Comment by jupmorenor** [comment]
Este es el formato sugerido para la respuesta, donde el campo "Data" contiene el texto que representa al archivo y que puede ser procesado por el software que lo recibe.
{
    "Data": "JVBERi0xLjQKMyAwIG9iago8PC9UeXBlIC9QYWdlCi9QYXJl...
    ...govSW5mbyAxMiAwIFIKPj4Kc3RhcnR4cmVmCjQyMTc0CiUlRU9GCg==",
    "Message": "Query successful",
    "Status": "200",
    "Success": true
}

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
