### ISSUE TITLE
Revisión de spagobi para generación de reportes

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#148]

**Comment by sigfried1982** [comment]
# Generación de reportes

Se debe descargar el diseñador de reportes birt(SpagoBI Studio o KnowageReportDesigner)
se puede seguir el tutorial descrito en http://www.aiknow.info/2018/03/07/knowage-create-data-reports-with-birt/
en caso que no se pueda generar el despliegue del reporte se puede generar directamente desde el servidor de SpagoBI se selecciona el item que se muestra a continuación
![image](https://user-images.githubusercontent.com/44048060/105435905-3c9a6580-5c2c-11eb-9eee-5f9459ff9444.png)
al seleccionar una de las carpetas de la parte izquierda se mostrarán los items alojados en dicha carpeta, se hará click en Crear documento>Generic documento tal como se muestra en la siguiente imagen
![image](https://user-images.githubusercontent.com/44048060/105436491-4b354c80-5c2d-11eb-83e7-efebba96a837.png)
con lo cual se pasará a la siguiente imagen en la cual se ingresarán los datos para el reporte 
![image](https://user-images.githubusercontent.com/44048060/105437009-402eec00-5c2e-11eb-8c0e-cb272da91912.png)
En el primer grupo se encuentran tres campos
- Etiqueta y Nombre deben ser únicos
- Descripción permite ingresar la descripción del reporte

En el campo datasource debe seleccionarse una fuente de datos ya creada
En el campo plantilla se cargará el archivo .rptdesign con la definición del reporte
posteriormente se seleccionará en la parte derecha de la pantalla la carpeta en la cual se alojará el reporte, en la parte superior derecha se encuentra un botón para guardar la definición del reporte, otro para guardar la definición y volver y otro que no guarda los cambios y vuelve.
si sólo guarda el reporte aparecerá una nueva sección para ingresar los parámetros requeridos por el reporte(son opcionales dependiendo de la definición del reporte)
![image](https://user-images.githubusercontent.com/44048060/105437528-42457a80-5c2f-11eb-9fa7-1b82ac153724.png)

## Utilizar parámetros en reportes
### Diseñador del reporte
Al crear un dataset se debe ingresar una consulta sql que consolidará los datos que se mostrarán en el reporte, en este momento se agrega en la clausula where las condiciones y se igualan a "?" tal como se muestra a continuación
![image](https://user-images.githubusercontent.com/44048060/105438381-e2e86a00-5c30-11eb-9069-5e1b624e519a.png)
una vez finalizada la edición de la consulta se da click en finalizar, con lo cual se pasa a la siguiente pantalla
![image](https://user-images.githubusercontent.com/44048060/105438714-89346f80-5c31-11eb-861d-9d6eed2bf610.png)
en la parte derecha se observan los campos que hacen parte del reporte en la izquieda debe seleccionarse Parameters
![image](https://user-images.githubusercontent.com/44048060/105438808-b2ed9680-5c31-11eb-9db0-61616b8a7914.png)
al editar uno de los parámetros aparecerá la siguiente pantalla
![image](https://user-images.githubusercontent.com/44048060/105439115-3effbe00-5c32-11eb-98ca-a9bc8e9d8b2a.png)

![image](https://user-images.githubusercontent.com/44048060/105439212-6c4c6c00-5c32-11eb-8232-9dd28f2e3d5f.png)
una vez completado este paso se real

![image](https://user-images.githubusercontent.com/44048060/105439390-c3ead780-5c32-11eb-88b1-7aa837f186f5.png)

### SpagoBI Server
Se diligencian los campos tal como se muestra en la siguiente image
![image](https://user-images.githubusercontent.com/44048060/105440651-ef6ec180-5c34-11eb-99bb-a5ee262b29f4.png)
luego se hace click en la lupa para seleccionar el parámetro en caso que ya exista o para la creación de uno nuevo
![image](https://user-images.githubusercontent.com/44048060/105440837-4d030e00-5c35-11eb-9106-57f002b08ad0.png)
si el parámetro existe se selecciona mediante los checks de la columna de la derecha, si es nuevo se debe hacer click en la lupa con el signo de +

![image](https://user-images.githubusercontent.com/44048060/105442016-b7b54900-5c37-11eb-863b-245ea0287409.png)

**Comment by sigfried1982** [comment]
## Fuentes y despliegue de los reportes

Los archivos fuentes de creación de los reportes se encuentran en https://drive.google.com/drive/u/1/folders/1tpysA0paGzDuIrpqJSxZLAULK99RFuIq

Se generan dos juegos de reportes uno para ser usado en pruebas y otro en producción tal como se muestra en la siguiente imagen,
![image](https://user-images.githubusercontent.com/44048060/107289485-1bf74b80-6a33-11eb-8a62-a130d08794dd.png)

Seis reportes para pruebas
![image](https://user-images.githubusercontent.com/44048060/107289560-3af5dd80-6a33-11eb-863f-56b1b4e354f6.png)

Seis reportes para producción
![image](https://user-images.githubusercontent.com/44048060/107289604-4ba65380-6a33-11eb-8192-00aed1bb64cc.png)

Resumén de comité
![image](https://user-images.githubusercontent.com/44048060/107289767-81e3d300-6a33-11eb-90c8-58f6a410a753.png)

Acta de comité
![image](https://user-images.githubusercontent.com/44048060/107289680-62e54100-6a33-11eb-9f1f-19268cc540ea.png)

Reporte de pares
![image](https://user-images.githubusercontent.com/44048060/107289862-a63faf80-6a33-11eb-849e-7333d182341e.png)

Reporte de categorías
![image](https://user-images.githubusercontent.com/44048060/107289951-c66f6e80-6a33-11eb-9a44-bbcde016eba0.png)

Reporte de títulos
![image](https://user-images.githubusercontent.com/44048060/107289987-d38c5d80-6a33-11eb-855a-206e9a61fc63.png)

Reporte total de puntos
![image](https://user-images.githubusercontent.com/44048060/107290023-e0a94c80-6a33-11eb-9244-aa4712a818a1.png)
