### ISSUE TITLE
Verificación y pruebas de las librerías consultadas - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#15]
Se debe verificar el funcionamiento de las librerías consultadas en #14, se debe revisar que el código de barras generado, funcione de forma similar  a los códigos de barras ya establecidos en el proyecto de condor.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se crea el controlado para generar una imagen png con el codigo de barras, esta funcón se configuro como una petición post, en la que envia en el cuerpo de la peticion la totalidad del codigo a realizar, por ejemplo:
`{
"Prueba": "41577099980004218020020172165022052466390000001382589620190802"
}`

La función por el momento crea la imagen en la raiz del proyecto y entrega como response:
`{
  "Type": "",
  "Code": "",
  "Body": [
    "Response:",
    {
      "Prueba": "41577099980004218020020172165022052466390000001382589620190802"
    }
  ]
}`

Se espera definir que hacer con la imagen y la forma como se va enviar la información requerida para generar el codigo desde el cliente.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifica funcionamiento del POST a la ruta: /generar_codigo del mid API, se genera la imagen en formato png del código de barras, la respuesta retornada por el servicio es:
![image](https://user-images.githubusercontent.com/14035745/67175648-855dd180-f38c-11e9-89b7-36f5efce701b.png)

Código generado en la raíz del directorio del API:
![image](https://user-images.githubusercontent.com/14035745/67175678-b63e0680-f38c-11e9-90b2-496595f149fd.png)

Se da por finalizada la tarea.
