### ISSUE TITLE
Realizar controlador en sga_mid para generación de alertas y resultados de solicitudes verificadas

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#155]

**Comment by CrissUD** [comment]
# Generación de alertas para indicar expiración de estado 

Se genera lógica en el cliente para indicar a los usuarios cuando una solicitud esta presentando un retraso debido a que la fecha de expiración del estado actual ya se ha pasado:

## Generación de componente

La advertencia se realiza en forma de botón dentro de la tabla, sin embargo a diferencia de una acción, este botón solo se debe presentar en aquellas solicitudes que presentan la condición antes planteada, para poder generar esto fue necesario la construcción de un nuevo componente que es la representación del botón dentro de la tabla y quien lleva la condición de cuando mostrarse, dicho componente se generó en el area de @theme/components: 

![image](https://user-images.githubusercontent.com/44172561/102551834-28dc6c00-408e-11eb-8926-c13b462d97b9.png)
![button_alert](https://user-images.githubusercontent.com/44172561/102551926-51fcfc80-408e-11eb-9bb1-8ccb9f64cf45.png)
![button_alert2](https://user-images.githubusercontent.com/44172561/102551988-6b05ad80-408e-11eb-8e0f-3c282f92806e.png)

## Incorporación de alerta en la tabla

Se realiza la incorporación del componente dentro de la tabla el cual se muestra en forma de un icono en esta para las solicitudes que tienen un estado con la fecha expirada: 
![image](https://user-images.githubusercontent.com/44172561/102552121-a0aa9680-408e-11eb-8eb7-bd677008ed1f.png)
Estado de solicitud expirado
![image](https://user-images.githubusercontent.com/44172561/102552163-b28c3980-408e-11eb-9307-7f66fb9a96fb.png)
Mensaje de alerta
![image](https://user-images.githubusercontent.com/44172561/102552194-c33caf80-408e-11eb-9d7b-10d3b16bf863.png)

**Comment by CrissUD** [comment]
# Generación de Alertas en Solicitud al registrarse

Se genera lógica para la revisión de solicitudes una vez estas se han registrados para comprobar que dicha solicitud no se ha presentado con anterioridad por parte del docente, para esto existen ciertos criterios a valuar según la producción académica que solicita el docente como se muestra en la siguiente imagen:
![image](https://user-images.githubusercontent.com/44172561/102552871-e74cc080-408f-11eb-8c12-d2c43402a6eb.png)

## Generación de controlador

Se genera un controlador dentro de **sga_mid** llamado **SolicitudProduccionController** el cual  se va a encargar además de la generación de alertas, de la generación automatica de puntos en las solicitudes verificadas que no requieren evaluador de par externo y la búsqueda de coincidencias de posibles solicitudes antes presentadas por otros docentes que ya tienen una valoración.

### Explicación de algoritmos para revisión y generación de alertas
A continuación se explican los algoritmos a grandes rasgos (Estos están sujetos a cambiar en el futuro)
 **POST_ALERT_SOLICITUD_PRODUCCION**
Es el método principal y el encargado de recibir la información completa de la solicitud y la producción y a partir de esto llamar a los métodos necesarios para realizar las validaciones según el tipo de producción académica recibida:
![post](https://user-images.githubusercontent.com/44172561/102553832-7e664800-4091-11eb-9265-dfe19e493034.png)
 **CHECK_TITLE**
Este algoritmo se encarga de comparar el titulo de la producción subida con todas las producciones subidas en el sistema por el mismo autor y a través del algoritmo **levenshtein**  se calcula la distancia entre los títulos, dicha distancia esta dada para que si dos cadenas de texto son exactamente iguales la distancia entre ellas será de 0, si las dos difieren en dos caracteres la distancia será de 2. 
La configuración actual esta en que si los títulos a comparar tienen una distancia de 6 o menos se generará una alerta de este tipo. 

![checktitle](https://user-images.githubusercontent.com/44172561/102554503-fbde8800-4092-11eb-8240-7200f6927d39.png)
 
**CHECKANNUALPRODUCTIONNUMBER**
Este algoritmo se encarga de revisar las producciones del mismo tipo y del mismo autor que se han solicitado y aceptado para el mismo año de publicación o difusión, este se realiza para ciertas producciones que tienen un limitante de producciones al año, cada vez que encuentra una producción del mismo tipo en el año de publicación de la solicitud actual, va a retornar un 1 que se ira acumulando para encontrar el numero de producciones del mismo tipo para ese año.

Existe un caso interno que es el de publicaciones impresas en el cual se debe revisar la fecha de radicación y además que las solicitudes dentro de ese periodo de tiempo sigan activas (aun no han entrado a comité y no han recibido una respuesta).

![checkannual](https://user-images.githubusercontent.com/44172561/102555346-968b9680-4094-11eb-8470-cf3b3b28b6f3.png)
***nota:** Falta validar si la solicitud esta en estado activo o inactivo* 
**CHECKISBN**
Este algoritmo esta relacionado con todas las producciones que son o hacen parte de un libro (Libros, capítulos de libros, traducciones de libros), el algoritmo se encarga de buscar en otras producciones del mismo autor y verificar si el ISBN no se repite con otra producción antes registrada.
![checkISBN](https://user-images.githubusercontent.com/44172561/102557276-c177e980-4098-11eb-9dff-e23ad5147aa0.png)
**CHECKDURATIONPOSTDOCTORADO**
Este algoritmo se encarga de revisar las producciones académicas de tipo, estudio Post Doctorado del docente y verificar que el numero de meses para completar dicho estudio supere los 9 meses, de lo contrario generará alerta:
![checkDuration](https://user-images.githubusercontent.com/44172561/102557480-48c55d00-4099-11eb-895a-3769ebc9d8fe.png)
**CHECKGRADEPOINTS**
Este algoritmo se activa para las producciones de tipo titulo de postgrado, se encarga de verificar las demás producciones subidas por el docente de este tipo y verificar que no sobrepase el limite de puntos de 140. 
![checkPoints](https://user-images.githubusercontent.com/44172561/102557640-ac4f8a80-4099-11eb-8f54-740b827d83c1.png)
***Nota:** Este algoritmo no se ha podido comprobar debido a que aun el sistema no ha generado puntuación previa.*
**CHECKLASTCHANGECATEGORY**
Este algoritmo se activa para las producciones tipo cambio de categoría y se encarga de revisar el ultimo cambio de categoría para comprobar si la solicitud ha cumplido el tiempo mínimo de lo contrario generará una alerta.
![checkCategory](https://user-images.githubusercontent.com/44172561/102558028-8a0a3c80-409a-11eb-821f-6a113d4945e4.png)
 ***Nota:** Este algoritmo no se ha podido comprobar debido a que aun el sistema no ha generado la resolución de solicitudes para tipo de categoria.*
**GENERATEALERTS**
Es el algoritmo encargado de generar las alertas según los resultados obtenidos por los anteriores algoritmos, se encarga de mirar las banderas y según el cumplimiento o no de estas, generará una alerta, una vez termine de generar las alertas se encarga de llamar al modelo que contiene la lógica para actualizar la solicitud con las nuevas observaciones.
![generateAlerts](https://user-images.githubusercontent.com/44172561/102558411-5b409600-409b-11eb-8974-45979afc1419.png)

**Comment by CrissUD** [comment]
# Lógica de generación de Alertas desde el cliente

Una vez el usuario (docente) registre una nueva solicitud, el sistema enviara todos los datos necesarios para que el api **sga_mid** realice el proceso de verificación y generación de alertas como un proceso interno y ajeno a la funcionalidad de la página web, esto quiere decir que el docente puede seguir realizando acciones dentro de la página web o incluso cerrar sesión o salir de la página y este proceso seguirá corriendo. 

En caso en que la solicitud enviada genere una alerta el secretario podrá ver estas alertas al revisar dicha solicitud:

* Registro de solicitud que activará varias alertas 
![image](https://user-images.githubusercontent.com/44172561/102559798-b7f18000-409e-11eb-9030-b0c94b860834.png)
* Revisión de alertas generadas
![image](https://user-images.githubusercontent.com/44172561/102559927-043cc000-409f-11eb-9f62-a6da35585c86.png)
* Alerta 1: coincidencia con títulos de otras producciones 
![image](https://user-images.githubusercontent.com/44172561/102559985-28000600-409f-11eb-94f6-64ca7dd9c745.png)
* Alerta 2: Numero de producciones en el año superada
![image](https://user-images.githubusercontent.com/44172561/102560039-45cd6b00-409f-11eb-8fc9-78581092f960.png)

**Comment by CrissUD** [comment]
# Agregación nuevos casos de alerta

A petición de oficina de docencia se agregan nuevos casos de generación de alertas:

### Explicación de algoritmos para revisión y generación de alertas
**CHECKREGISTERNUMBER**
Este algoritmo se encarga de revisar el numero de registro para producciones académicas relacionadas con patentes o producciones de software para verificar que este registro no se ha presentado con anterioridad
![checRegisterNumber](https://user-images.githubusercontent.com/44172561/103490654-4a0dbe00-4deb-11eb-83f5-3ed474bf4bd3.png)

**CHECKISSNVOLNUMBER**
Este algoritmo se encarga de revisar el ISSN, volumen y numero de revista para producciones académicas relacionadas con artículos (Artículos completos, Artículos cortos, Páginas editoriales), para verificar que alguna de estas producciones no se han repetido con anterioridad.
![checISSNVolNum](https://user-images.githubusercontent.com/44172561/103490757-ff407600-4deb-11eb-94d4-d2956f6f5f2f.png)

**CHECKEVENTNAME**
Este algoritmo se encarga de revisar el nombre de evento para producciones relacionadas con videos, Cinematográficas, Fonografías y Obras Artísticas, para verificar que no se han subido varias producciones de un mismo evento:
![checkEventName](https://user-images.githubusercontent.com/44172561/103490837-94436f00-4dec-11eb-9793-8daff642206d.png)

**CHECKRANGEGRADE**
Este algoritmo se encarga de revisar que la solicitud de título que suba el docente no sea de menor rango a un título presentado con anterioridad, Por ejemplo si un docente ya presento una maestría no es posible realizar una solicitud de especialización:
![checkrangeGrade](https://user-images.githubusercontent.com/44172561/103490927-36635700-4ded-11eb-82d3-5562894d9ef0.png)

**Comment by Camiloqui** [comment]
### **Generacion de resultado para solicitudes que no requieren revision de par academico**
**Expllicacion de algoritmos de resultados de solicitudes verificadas**
**GENERATERESULT**
Este algoritmo recibe la solicitud del docente, con su respectiva produccion academica, observaciones etc.
aca buscamos el subtipo produccion Id para poder filtrar que tipo de solitud es. en este caso si es de titulo hara un llamado diferente de funcion, tambien dejamos los metadatos de la solicitud separados en otra variable para enviarla a una funcion diferentes, luego de que las funciones retornan las variables valor y autores se hara el respectivo calculo del resultado, en otra funcion llamada **addResult** que le damos la solicitud de produccion, el subtipo produccion id y las variables valor y autor
![image](https://user-images.githubusercontent.com/19983790/103547166-aa434500-4e69-11eb-9d66-593bc881e09f.png)

**findcategoryPoints**
Este algoritmo lo que realiza es buscar dentro de un for, el metadato, es decir la solicitud tiene varias metadatos y el for recorrera cada metadato y lo que hacer es buscar la cantidad de autores que tiene la solicitud (si aplica) y el valor es para registrar que valor tiene el metadato en esas id de metadato que serian (categoria Revista, categoria premio, etc) como el for es fuera de la funcion siempre devolvera un valor distinto pero dicho valor solo aplicara en las solicitudes que aplique
![image](https://user-images.githubusercontent.com/19983790/103548731-d8298900-4e6b-11eb-822f-e8ac8dde3210.png)

**findgradepoints**
Este algoritmo lo que hace es calcular en cuantas solicitudes/producciones del docente que envia la solicitud son de tipo titulo, es decir que calculara si el docente tiene titulos de especializacion, maestria o doctorado, luego de verificar cuantas tiene, hace calculos diferentes, si tiene 2 especializaciones y la solicitud de puntos de asignacion es de tipo especializacion devolvera valor 0 y autores 1 en la funcion de generateresult entendera que debera darle 0 puntos a la solicitud. en general dara una asignacion de puntos segun el caso de maestrias, especializaciones tenga en el momento. la idea es que lo calcule segun las solicitudes que tenga cerradas, puesto que son solicitudes ya calificadas y que son aprobadas o rechazadas, ya que al hacerlo sobre solicitudes activas pueden ocasionar problemas en el momento de asignacion de puntos, 
![image](https://user-images.githubusercontent.com/19983790/103549053-630a8380-4e6c-11eb-987e-ba8fbf71bd84.png)
![image](https://user-images.githubusercontent.com/19983790/103549072-6aca2800-4e6c-11eb-9ebc-c945ca91e3a8.png)
![image](https://user-images.githubusercontent.com/19983790/103549084-71589f80-4e6c-11eb-989d-f876168079cd.png)
**addResult**
Este codigo recibe la solicitud del docente actual, el id subtipo de la solicitud, el valor y los autores (si aplica) aca la funcion hace una peticion a puntaje_subtipo_produccion lo que traera un array con los puntajes asignados segun el subtipo de produccion, es decir si es categoria revista traera 4 resultados para cada categoria (A1,A2,B,C) y con el valor que ya tiene asignado sabra que tipo de categoria es la solicitud de esta manera solamente extraera el resultado de dicha categoria, calcula el puntaje segun la cantidad de autores que tenga y devolvera un json con el puntaje a la solicitud del docente de la siguiente manera "Puntaje":"0.0" este era guardado en el atributo "Resultado" de la solicitud del docente 
![image](https://user-images.githubusercontent.com/19983790/103549565-37d46400-4e6d-11eb-88ec-d67e25824ae6.png)
![image](https://user-images.githubusercontent.com/19983790/103549637-4de22480-4e6d-11eb-95ab-3e81c50a7c70.png)

**Comment by Camiloqui** [comment]
**El controlador de solicitud_produccion put** 
lo que realiza el controlador es llamar a la funcion GenerateResult dentro de los modelos, que tiene el sga_mid y devuelve la solicitud actualizada
![image](https://user-images.githubusercontent.com/19983790/103550076-f7c1b100-4e6d-11eb-80cb-05d8efed8bc0.png)

**Comment by fabianbarreto02** [comment]
A la espera de aprobación del usuario

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
