### ISSUE TITLE
Ajustar Mid para asignación de coordinador - 8 horas - 2 semanas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#16]
Se debe desarrollar una función que al momento de asignar un coordinador a un proyecto académico, y este ya cuenta con un coordinador ya asignado, esta función deberá desactivar el campo activo del coordinador pasado y crear el nuevo registro del coordinador activo. 

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo.

**Comment by fabianbarreto02** [comment]
Se desarrolla la función que desactiva los coordinadores asignados al proyecto, si este cuenta con alguno, y asigna el nuevo coordinador al proyecto académico, se espera revisar problema de fecha de inicio con ayuda de @mafeave

**Comment by mafeave** [comment]
El ajuste de la fecha de finalización se realizará en un issue nuevo.
