### ISSUE TITLE
Realizar Lógica para paquetes

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#173]

**Comment by CrissUD** [comment]
# Generación de paquetes

Se crea Lógica para generación de paquetes, una vez se escojan las solicitudes en el cliente para la generación de un nuevo paquete para revisión ante un comité a continuación se muestra el código:
## Controlador Sga_mid
![postPaqueteControlSga](https://user-images.githubusercontent.com/44172561/103492693-a0362d80-4dfa-11eb-964b-72f31cc1d07d.png)

## Modelo Sga_mid
![postPaqueteModeloSga](https://user-images.githubusercontent.com/44172561/103492715-c0fe8300-4dfa-11eb-83ac-741174973d1e.png)

## Controlador Solicitud_Crud
![postPaqueteControlSolicitud](https://user-images.githubusercontent.com/44172561/103492750-fd31e380-4dfa-11eb-92d4-f1137a0d8b84.png)

## Modelo Solicitud_Crud
![postPaqueteModeloSolicitud](https://user-images.githubusercontent.com/44172561/103492758-0622b500-4dfb-11eb-9f22-83dc37419cb3.png)

**Comment by CrissUD** [comment]
# Consulta de solicitudes dentro de un paquete 

Se crea lógica para el filtrado de solicitudes que están dentro de un paquete:

## Información general de paquetes

### Controlador Solicitud_Crud
![getPaqueteControlSolicitud](https://user-images.githubusercontent.com/44172561/103492825-a24cbc00-4dfb-11eb-81aa-9d4b15cc5d68.png)

### Modelo Solicitud_Crud
![getPaqueteModeloSolicitud](https://user-images.githubusercontent.com/44172561/103492844-cdcfa680-4dfb-11eb-9bdf-0253a38bb4f5.png)

## Solicitudes dentro de un paquete

### Controlador Sga_Mid
![getPaqueteControlSga](https://user-images.githubusercontent.com/44172561/103492883-16875f80-4dfc-11eb-9aae-5c144dc30772.png)

### Modelo Sga_Mid
![getPaqueteModeloSga](https://user-images.githubusercontent.com/44172561/103492890-2141f480-4dfc-11eb-8c66-3ad640253c2a.png)

**Comment by CrissUD** [comment]
# Modificación de estados y solicitudes dentro de paquetes

Se realiza lógica para los casos de modificación dentro de un paquete

## Controlador Sga_mid
![putPaqueteControlSga](https://user-images.githubusercontent.com/44172561/103493005-d5437f80-4dfc-11eb-8828-480e6333f09f.png)

## Modelo Sga_mid
![putPaqueteModeloSga](https://user-images.githubusercontent.com/44172561/103493012-daa0ca00-4dfc-11eb-9dbd-ecd5580fb3f4.png)

## Controlador Solicitud_Crud
![putPaqueteControlSolicitud](https://user-images.githubusercontent.com/44172561/103493015-e1c7d800-4dfc-11eb-89b4-bd9e8a160855.png)

## Modelo Solicitud_Crud
![putPaqueteModeloSolicitud](https://user-images.githubusercontent.com/44172561/103493016-e5f3f580-4dfc-11eb-8663-faaf60af0e8e.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
