### ISSUE TITLE
Ajustar MID de proyecto_academico incluyendo el campo de fecha de finalización del coordinador - 6 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#19]
Teniendo en cuenta las observaciones dadas en la [issue](https://github.com/udistrital/sga_cliente/issues/35), se debe ajustar el mid para que el momento de asignar un coordinador nuevo, registre la fecha de finalización del coordinador anterior, la issue debe cumplir con los siguientes requerimientos:

- [x] La funcionalidad debe registrar la fecha de finalización al momento de asignar un nuevo coordinador de forma oculta al usuario.
- [x] Utilizar la libreria [time_bogota](https://github.com/udistrital/utils_oas), para la captura de la fecha .

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza el ajuste de la funcion para la asignacion del coordinador a un proyecto, registra la fecha de finalizacion lo deshabilita y crea la nueva asignacion, se observa que al usar la libreria dispuesta por util oas para capturar la fecha actual de bogota presenta un erro ps cada ves que se realiza un cambio resta a la hora ya resgistrada las 5 horas de diferencia de colombia, se debe revisar el uso de esa libreria para cruds y mid.

Se espera revisión por parte de @mafeave

**Comment by mafeave** [comment]
Se verifica desactivación y registro de la fecha de finalización del coordinador, función verificada con el siguiente cuerpo de la petición POST:
```
{
  "Activo": true,
  "DependenciaId": 0,
  "FechaInicio": "2019-09-11T11:29:55Z",
  "PersonaId": 1,
  "ProyectoAcademicoInstitucionId": {
    "Id": 1
  },
  "RolId": 0
}
```
