### ISSUE TITLE
Pruebas unitarias API MID creación proyecto curricular

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#20]
Crear pruebas unitarias para endpoints que permiten crear un proyecto curricular.
- [x] Las pruebas unitarias del API MID prueban las lineas de código que permite crear un proyecto curricular.

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de ejecución de las pruebas de creación del proyecto curricular

![imagen](https://user-images.githubusercontent.com/25555966/67992390-7f78b380-fc0a-11e9-939c-9f29def60214.png)

**Comment by mafeave** [comment]
Verificadas las pruebas, se da por finalizada la tarea.
