### ISSUE TITLE
Realizar lógica de rechazo de invitación por par externo

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#205]

**Comment by CrissUD** [comment]
# Lógica de rechazo de solicitud par externo

Se genera lógica de rechazo en el sga mid a través de una petición get ya que el servicio se quiere dejar publico y así poder cambiar el estado de una solicitud a través de una petición basada en un link:

## Control Sga_Mid
![rechazocontrolsga](https://user-images.githubusercontent.com/44172561/103550077-5a1eaf80-4e76-11eb-85fb-743e8b70ac3a.png)

## Modelo Sga_Mid
![rechazomodelosga](https://user-images.githubusercontent.com/44172561/103550220-93efb600-4e76-11eb-9b5e-f1fa4fd7e545.png)

Dentro de la lógica del rechazo se reutilizan otras funcionalidades de los modelos como el de **PutSolicitudDocente** que se encarga de actualizar el estado y la evolución del mismo dentro de la solicitud

**Comment by CrissUD** [comment]
# Resultado rechazo petición

Una vez una petición es rechazada el estado de la solicitud cambiara a **RECHAZADA** y al usuario le saldrá un mensaje como este:
![image](https://user-images.githubusercontent.com/44172561/103551084-d2d23b80-4e77-11eb-8869-5a4f1ee978ea.png)

También se creo una logica adiciona para los casos en que un par externo oprima varias veces el link de rechazo, en caso de que la solicitud ya tenga el estado de rechazo, no se realiza el flujo de actualización de estado sino que retorna el sigiente mensaje:
![image](https://user-images.githubusercontent.com/44172561/103551190-feedbc80-4e77-11eb-90e0-cf6ff638b1d5.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
