### ISSUE TITLE
Pruebas unitarias API MID de los registros calificados y de acreditación para un proyecto curricular y asignación de coordinador

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#21]
Crear pruebas unitarias para los enpoints que permiten registrar registros calificados y de acreditación, ademas del registro de coordinador.
- [x] Las pruebas unitarias del API MID prueban las lineas de código que permite crear registros de acreditación.
- [x] Las pruebas unitarias del API MID prueban las lineas de código que permite crear registros de alta calidad.
- [x] Las pruebas unitarias del API MID prueban las lineas de código que permiten agregar un coordinador a un proyecto curricular.

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de ejecución de las pruebas

![imagen](https://user-images.githubusercontent.com/25555966/68088446-5be18300-fe2d-11e9-8bd1-bc6770b7ee1c.png)
![imagen](https://user-images.githubusercontent.com/25555966/68088452-66038180-fe2d-11e9-85a4-2ef88e44921b.png)

**Comment by mafeave** [comment]
Se verifican las pruebas relizadas, se da por finalizada la tarea.
