### ISSUE TITLE
Inserts API Evaluación

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/sga_mid#219]

**Comment by EstefaniaPerezTorres** [comment]
### Inserts tabla item, seccion y tipo_evaluacion

[Archivo de excel para inserts](https://docs.google.com/spreadsheets/d/1_8gRFa4F8554fgkyY-z_nwyX-KGY8UrpGCr-9SWNiMo/edit?usp=sharing)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
