### ISSUE TITLE
Realizar función para consulta los los estados de pago y fechas de vencimientos de los recibos de un tercero especifico 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#226]
Se debe realizar una función que reciba del cliente un json con la información del nuemero de recibo (recibo_inscripcion_id) y el año del recibo con la fecha de creación, este json debe tener todos lo recibos que cuente ese tercero, la función recibe ese json  con uno o varios recibos  se debe consultar con el [servicio ](http://jbpm.udistritaloas.edu.co:8280/services/recibos_pago/consulta_recibo/8702/2021)de consulta uno a uno (for) los recibos que tiene el tercero, la petición requiere numero unico y año para la consulta, el servició retorna lo siguiente :

![image](https://user-images.githubusercontent.com/43799065/104769535-6ee42880-573d-11eb-9425-0810b470a678.png)

se ese response se debe extraer la información e ir construyendo un arreglo para cada recibo con fecha ordinaria,  pago (N/S), fecha extraordinaria, estado (A/I), con ese arreglo se debe ajustar en el cliente para para que se actualice el boton de pago o inscripcion con el campo pago y si el recibo esta vencido o aun no se puede se puede pagar el recibo, la issue debe cumplir con los siguientes requerimientos:

- [x] Enviar el arrglo del json necesario para la función que se va a desarrollar 
- [x] Desarrollar la función de consulta de los recibos para el tercero a consultar
- [x] Construir el responce como se suguiere 
- [x] Implementar la logica para los botones y la información si esta vencido el recibo

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se da por finalizada esta issue

**Comment by fabianbarreto02** [comment]
se valida la issue
