### ISSUE TITLE
Modulo de coincidencia entre solicitudes

### ISSUE THREAD

**Issue by CrissUD** [udistrital/sga_mid#235]

**Comment by CrissUD** [comment]
# Lógica en sga para revisión de coincidencias de solicitudes

Pensando en las solicitudes que puedan estar repetidas ya que algún otro docente con el que se realizo una misma producción realizo su debido proceso de solicitud en el sistema,  se crea la lógica inicial para revisar estos casos,

## Generación nuevo tipo de observación  
Lo primero que se realiza es crear un nuevo tipo de observación que será una alerta de coincidencia, así en caso de que una solicitud coincida con una solicitud anteriormente finalizada de otro docente se generará este tipo de observación, esto se realiza con una migración con el respectivo sql; 
![image](https://user-images.githubusercontent.com/44172561/105511199-a69f2300-5c9d-11eb-9369-1b1e58353714.png)

## Lógica en SGA_MID 

En el Sga_mid se crea un nuevo modelo que se encarga de verificar que la solicitud  coincida con la solicitud finalizada de algun otro docente y si es el caso genera la alerta de coincidencia: 
![verificaiconCoincidencia](https://user-images.githubusercontent.com/44172561/105511457-e7973780-5c9d-11eb-91e3-fdca20b354b3.png)

Este modelo es utilizado desde el controlador de **solicitud_produccion** asi que esta revisión se realiza justo despues de revisar el otro tipo de alertas:

![sga controlador verificar coincidencia](https://user-images.githubusercontent.com/44172561/105511728-3a70ef00-5c9e-11eb-912e-6c2e751ec4bb.png)

**Comment by CrissUD** [comment]
# Lógica en el cliente para modulo de coincidencias 

Si una solicitud presenta alguna de estas advertencias por coincidencias dentro de la solicitud a revisar podrá verse la etiqueta de la advertencia con un color y logo distinto de la siguiente manera:

![image](https://user-images.githubusercontent.com/44172561/105511955-86bc2f00-5c9e-11eb-84e8-d3071403219c.png)


Una vez se de click en el botón y para generar una logica a parte se llama a un nuevo componente llamado **list_coincidencias**:
![image](https://user-images.githubusercontent.com/44172561/105512120-b9febe00-5c9e-11eb-8a91-3e3670f96b5a.png)

En ella se consulta a detalle cada una de las solicitudes cuyo Id quedo registrado en la alerta, este componente se llama de forma de pop up y se ve de la siguiente manera: 

![image](https://user-images.githubusercontent.com/44172561/105512263-e0bcf480-5c9e-11eb-9f46-0cb9e151a56c.png)

Al darle en el boton de ver se podrá ver a detalle la solicitud: 
![image](https://user-images.githubusercontent.com/44172561/105512321-f5998800-5c9e-11eb-9e19-063146c573ae.png)

**Comment by CrissUD** [comment]
# Lógica para verificación de coincidencia

Una vez se revisan las solicitudes que coinciden, se entra a una lógica para determinar si es necesario realizar una clonación de evaluaciones y resultado (para los casos en que la producción deba entrar al proceso de evaluación docente) para posteriormente clonar el resultado, o solamente haya que clonar el resultado (para los casos en que la producción no necesite entrar en el proceso de evaluación):

![aceptCoincidence](https://user-images.githubusercontent.com/44172561/106159473-d42f1500-6152-11eb-875b-3621c517e7df.png)


Si pasa por el proceso de clonación de evaluaciones se llama al sga_mid para realizar dicho proceso y posteriormente se llama al método de clonación de resultado:
![cloneResult](https://user-images.githubusercontent.com/44172561/106160019-6505f080-6153-11eb-9cce-0afc16190650.png)


Finalmente desde el método de clonación de resultado se llama al método updateSolicitudDocente para que el resultado clonado quede registrado además de un cambio de estado para que pase a preparación para revisión de comité:
![updateSolicitud](https://user-images.githubusercontent.com/44172561/106160227-9aaad980-6153-11eb-830f-178c96953a1e.png)

**Comment by CrissUD** [comment]
# Lógica para clonación de solicitudes tipo evaluación

Una vez se verifica la coincidencia entre solicitudes y esta contiene un tipo de producción que ha pasado por el proceso de evaluación de par externo se procede a realizar la clonación de evaluaciones creando nuevas solicitudes tipo evaluación que apuntan a la misma evaluación registrada en **evaluaciones_crud** y que contiene el mismo resultado y referencias:

![cloneEvaluation](https://user-images.githubusercontent.com/44172561/106160830-42280c00-6154-11eb-9578-c4924e1d5b38.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
