### ISSUE TITLE
Pruebas unitarias de consulta y modificación de proyecto curricular

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#25]
Crear pruebas unitarias para los enpoints que permiten consultar y modificar proyectos curriculares.

- [x] Las pruebas unitarias del API MID prueban las lineas de código que permiten consultar proyectos.
- [x] Las pruebas unitarias del API MID prueban las lineas de código que permiten modificar proyectos.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea teniendo en cuenta que el put de la info basica del proyecto corresponde a el crud y no al mid, se agregan pruebas para los siguientes endpoints:
- consulta_proyecto_academico/inhabilitar_proyecto/:id (PUT)
- consulta_proyecto_academico (GET)
- consulta_proyecto_academico/:id (GET)

**Comment by JuanPiedrahita** [comment]
Se agrega evidencia de ejecución

![imagen](https://user-images.githubusercontent.com/25555966/68537992-8ce51a80-033b-11ea-9a1f-e5cd8f681ffe.png)
![imagen](https://user-images.githubusercontent.com/25555966/68537996-94a4bf00-033b-11ea-8c86-b8b01217ff45.png)
![imagen](https://user-images.githubusercontent.com/25555966/68538000-a4240800-033b-11ea-90d3-71eb60456d1b.png)
![imagen](https://user-images.githubusercontent.com/25555966/68538003-ab4b1600-033b-11ea-93bd-d2ea17e48a90.png)

**Comment by mafeave** [comment]
Se verifica la ejecución de las pruebas de consulta y modificación de proyecto curricular, se da por finalizada la tarea.
