### ISSUE TITLE
Realizar la funcionalidad para utilizar el servicio de creación del recibo de pago 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#255]
Se debe desarrollar la funcionalidad para realizar el registro del recibo de pago con el servicio dado, la función debe consumir el servicio dado, se debe recolectar la información necesario para enviar al servicio, el servicio se consume con el siguiente objeto:

Servicios:

- https://autenticacion.portaloas.udistrital.edu.co/apioas/recibos_pago/v1/recibosPagoProxy
- http://jbpm.udistritaloas.edu.co:8280/services/recibosPagoProxy

`{
    "creaTransaccion": {
        "objTransaccion": {
            "codigo": 24682,
            "nombre": "prueba nombre",
            "apellido":"apellido",
            "correo":"correo@correo.com",
            "proyecto":80,
            "tiporecibo":15,
            "concepto":"Inscripcion Virtual",
            "valorordinario":1000,
            "valorextraordinario":2000,
            "cuota":1,
            "fechaordinario":"31/01/2021",
            "fechaextraordinario":"15/02/2021",
            "aniopago":2020,
            "perpago":3,
            "codigovalidacion":"Socrates3164lhbydqo",
            "secuencia":0
        }
    }
}` 

De los cuales se tiene:

- codigo: Documento del aspirante
- tiporecibo:15 (siempre)
- cuota: 1(siempre)
- secuencia 0 (siempre)

Después de generar el recibo se debe caputar el numero del recibo y realizar el registro en inscripciones crud, tambien quitar el boton x que oculta todo el componente de preinscripcion , la issue debe cumplir con los siguientes requerimiento:

- [x] Ajustar y recopilar los datos que se necesaitan para consumir el servicio 
- [x] Consumir y generar el recibo con el objeto establecido y el servicio 
- [x] Realizar el registro en el api de inscripcion_crud
- [x] Quitar el botón x que oculta todo el componente de preinscripcion

**Comment by jupmorenor** [comment]
Se da inicio con la solución de esta tarea.

**Comment by jupmorenor** [comment]
Se da por finalizada esta tarea

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
