### ISSUE TITLE
Realizar función post deshabilitar anterior, habilitar nuevo para actualizar los datos con solicitudes previamente aprobada

### ISSUE THREAD

**Issue by gabrielablanco** [udistrital/sga_mid#272]
Se debe realizar una función post a nivel mid en donde guarda los nuevos datos del estudiante siempre y cuando la solicitud esté aprobada, para ello se debe deshabilitar los datos antiguos y mostrando los nuevos. La issue debe cumplir los siguientes requerimientos:
- [x] Función post a la API de terceros con la nueva información siempre y cuando la solicitud esté previamente aprobada
- [x] Deshabilitar los datos anteriores del estudiante (Activo=false)
- [x] Cargar en el cliente la información actualizada

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de esta issue

**Comment by gabrielablanco** [comment]
Se presentaron problemas a la hora de generar POST en la tabla tercero para actualizar el nombre (FK duplicada) por lo que para la actualización de nombre se hizo un PUT a ésta. En caso tal de que se necesite el histórico de la actualización de nombre se puede buscar por el número de solicitud

**Comment by gabrielablanco** [comment]
Se da por finalizada la issue

**Comment by jupmorenor** [comment]
Esta issue fué finalizada satisfactoriamente
