### ISSUE TITLE
Ajustar registro de proyecto académico con llamada de transacción de OIKOS - API mid

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#30]
Ajustar el servicio de registro de un proyecto academico para que consuma la transacción de creación de dependencia de OIKOS, ver https://github.com/udistrital/oikos_api/issues/10
- [x] El servicio del mid del creación de proyecto consume el servicio de creación de dependencia de Oikos.
- [x] Crear en el sistema oikos el proyecto académico.
- [x] Registrar en la base de datos el id del nuevo proyecto académico registrado en oikos.
- [x] Se debe consultar la facultad a la que esta asociado el proyecto académico en oikos.
- [x]  El cliente debe mostrar la facultad donde se encuentra asociado el proyecto académico.

**Comment by JuanPiedrahita** [comment]
Se envia data json con el siguiente formato: 

```json
{
   "PadreId": {
      "Id": 5
    },
    "HijaId": {
      "Nombre": "NombreDependenciaHija",
      "TelefonoDependencia": "Número Dependencia Hija",
      "CorreoElectronico": "Correo Dependencia Hija"
    }
}
```

**Comment by JuanPiedrahita** [comment]
Se corrige la transacción y se da por terminada la tarea.

**Comment by mafeave** [comment]
Se hace prueba de registro de un nuevo proyecto académico, para verificar el llamado de la transacción de OIKOS, en el cliente se muestra mensaje de registro correcto, pero en la consola del API mid, se muestra el siguente mensaje de error:
![Captura de pantalla de 2019-11-18 07-41-56](https://user-images.githubusercontent.com/14035745/69053509-8d368300-09d7-11ea-997f-4aafeac5aa11.png)

Tener en cuenta que el registro en OIKOS, debe quedar antes del registro en el API de proyecto_academico_crud, ya que la tabla proyecto_academico_institucion, tiene el campo de dependencia_id, que debe llenarse con el Id devuelto por la transacción de OIKOS.

**Comment by JuanPiedrahita** [comment]
SE valida error desd el mid para que no se pueda crear el proyecto si no se crea la dependencia

![image](https://user-images.githubusercontent.com/25555966/69378622-bd528000-0c7c-11ea-9e44-af9c4d3212f7.png)

**Comment by JuanPiedrahita** [comment]
Se valida que el error era de las secuencias de la base de datos de oikos, el problema ya fue solucionado.

**Comment by JuanPiedrahita** [comment]
SE agrega consulta para getAll del proyecto y GetOne.

**Comment by JuanPiedrahita** [comment]
Se da por terminada la tarea

**Comment by mafeave** [comment]
Se hace merge a la rama dev y test, y se verifica la funcionalidad desde el despliegue en el ambiente de pruebas. Se da por finalizada la tarea.
