### ISSUE TITLE
Creación del flujo para guardar documento de condición de discapacidad 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#313]
Se debe desarrollar el flujo para almacenar y consultar los documentos soporte para las condiciones de discapacidad, para esto se debe cumplir con los siguientes requerimientos:

- [x] Se debe crear el migrations en el api de tercero un info_complementaria con nombre Documento_soporte y perteneciente al grupo de información complementaria con Id= 1 o Tipo Discapacidad
- [x] Crear mensaje de alerta al seleccionar si tiene alguna discapacidad  informar al usuario con el siguiente mensaje "Señor usuario, si usted tiene mas de una condición de discapacidad, por favor subir un solo documento en formato pdf con todas las certificaciones necesarias."
- [x] Ajustar los métodos de post, get y put para la relación del documento en el tag de información básica/ información  característica

**Comment by JQuinteroC** [comment]
Se concluye desarrollo y se espera aprobación

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se da por finalizada la issue.
