### ISSUE TITLE
Ajustar registro de proyecto académico para enviar ID de la dependencia registrada en OIKOS - 5 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#32]
Se debe realizar el ajuste durante el registro del proyecto académico, pues actualmente se registra el id de la facultad y no el id del proyecto creado, se debe registrar el id del proyecto creado en oikos, el issue debe cumplir con los siguientes requerimientos:

- [ ] Crear en el sistema oikos el proyecto académico.

- [ ] Registrar en la base de datos el id del nuevo proyecto académico registrado en oikos.

Lider Tecnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by JuanPiedrahita** [comment]
SE cierra este issue debido a que la tarea se transfiere y se llevará a cabo en el issue https://github.com/udistrital/sga_mid/issues/30
