### ISSUE TITLE
Verificar consulta de datos de proyecto académico, y sí tiene la dependencia asociada - 5 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#33]
Con el ajuste realizado en #32 se debe realizar el ajuste al momento de consulta del proyecto pues para el usuario debe observar la facultad a cual pertenece el proyecto académico, la issue debe cumplir con los siguientes requerimientos:

- [ ] Se debe consultar la facultad a la que esta asociado el proyecto académico en oikos.

- [ ]  El cliente debe mostrar la facultad donde se encuentra asociado el proyecto académico.

Lider tecnico @mafeave

**Comment by JuanPiedrahita** [comment]
SE cierra este issue debido a que la tarea se transfiere y se llevará a cabo en el issue https://github.com/udistrital/sga_mid/issues/30
