### ISSUE TITLE
Registro de datos de contacto de los terceros en el formulario de información familiar

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#38]
Agregar a la transacción de registro de información de terceros la funcionalidad para guardar los datos de contacto del tercero.
- [x] El sistema almacena los datos de contacto de los terceros.

**Comment by JuanPiedrahita** [comment]
Se revisan avances del core para determinar en que tabla se debe almacenar la información de contacto.

Según modelose debe almacenar la información en la siguiente tabla:

![image](https://user-images.githubusercontent.com/25555966/69729367-2bbb9600-10f4-11ea-9817-c38fb7636da7.png)

Además segun migrations se ve que se debe almacenar la información asociado a estos tipos de datos:
```sql
	m.SQL("INSERT INTO terceros.info_complementaria (nombre, codigo_abreviacion, activo, grupo_info_complementaria_id, fecha_creacion, fecha_modificacion) VALUES ('TELEFONO', 'TELEFONO', TRUE, 10, LOCALTIMESTAMP, LOCALTIMESTAMP);")
	m.SQL("INSERT INTO terceros.info_complementaria (nombre, codigo_abreviacion, activo, grupo_info_complementaria_id, fecha_creacion, fecha_modificacion) VALUES ('CELULAR', 'CELULAR', TRUE, 10, LOCALTIMESTAMP, LOCALTIMESTAMP);")
	m.SQL("INSERT INTO terceros.info_complementaria (nombre, codigo_abreviacion, activo, grupo_info_complementaria_id, fecha_creacion, fecha_modificacion) VALUES ('CORREO', 'CORREO', TRUE, 10, LOCALTIMESTAMP, LOCALTIMESTAMP);")
	m.SQL("INSERT INTO terceros.info_complementaria (nombre, codigo_abreviacion, activo, grupo_info_complementaria_id, fecha_creacion, fecha_modificacion) VALUES ('DIRECCIÓN', 'DIRECCIÓN', TRUE, 10, LOCALTIMESTAMP, LOCALTIMESTAMP);")
	m.SQL("INSERT INTO terceros.info_complementaria (nombre, codigo_abreviacion, activo, grupo_info_complementaria_id, fecha_creacion, fecha_modificacion) VALUES ('CODIGO_POSTAL', 'CODIGO_POSTAL', TRUE, 10, LOCALTIMESTAMP, LOCALTIMESTAMP);")
```

**Comment by JuanPiedrahita** [comment]
Se empieza a avanzar en la transacción

**Comment by JuanPiedrahita** [comment]
Se hace merge de los cambios recientes de terceros https://github.com/udistrital/terceros_crud/pull/19

**Comment by JuanPiedrahita** [comment]
https://github.com/udistrital/terceros_crud/commit/4b0e59eebdd9454716f039358bf5447a9ba18272

**Comment by JuanPiedrahita** [comment]
Se registra información de contacto de los terceros, se adjunta evidencai y se da por terminada la tarea.

![image](https://user-images.githubusercontent.com/25555966/69750342-88ca4280-111a-11ea-9bdd-9c20947ed457.png)

**Comment by mafeave** [comment]
Se realiza pull request a dev con revisión por parte del Core, ver https://github.com/udistrital/terceros_crud/pull/25

**Comment by mafeave** [comment]
Se verifica el registro de la información familiar para un tercero
![Captura de pantalla de 2019-12-03 21-14-40](https://user-images.githubusercontent.com/14035745/70111100-2c39bc80-161f-11ea-9f21-753d0f796661.png)

Para tener en cuenta: el tercero que va relacionado, debe ser el que está logueado en el sistema.
