### ISSUE TITLE
Ajustar MID para los formulario informacion personal de inscripcion tipo pregrado - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#39]
Se debe realizar la funcionalidad del registro de información personal en el tipo de inscripción pregrado,  se debe tener en cuenta la información establecida en el [documento](https://docs.google.com/document/d/1iaDwspU-YRdF6NVf1VJ89omQIlNs4x3HDkgCxSjQz9U/edit),  el mid debe cumplir con los siguientes requerimientos:
 
- [x] La funcionalidad debe registrar la informaón basica en el Api de terceros desarrollado por el equipo core.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Este es el body para realizar la petición post

{ 
"PrimerNombre": "fabian 3",
    "SegundoNombre": "david",
    "PrimerApellido": "barreto",
    "SegundoApellido": "sanchez",
    "TipoIdentificacion": {
        "Id": 3,
        "Nombre": "CÉDULA DE CIUDADANÍA",
        "Descripcion": "CÉDULA DE CIUDADANÍA",
        "CodigoAbreviacion": "CC",
        "Activo": true,
        "NumeroOrden": 0,
        "FechaCreacion": "2019-11-07T20:38:40.920912Z",
        "FechaModificacion": "2019-11-07T20:38:40.920912Z"
    },
    "NumeroIdentificacion": "1118559031",
    "EstadoCivil": {
        "Id": 8,
        "Nombre": "SOLTERO",
        "CodigoAbreviacion": "SOLTERO",
        "Activo": true,
        "TipoDeDato": "",
        "GrupoInfoComplementariaId": {
            "Id": 2,
            "Nombre": "Estado Civil",
            "Descripcion": "Tipos de Estado Civil que puede tener un tercero / persona_natural.",
            "CodigoAbreviacion": "Grupo_2",
            "Activo": true,
            "FechaCreacion": "2019-11-07T20:38:40.825993Z",
            "FechaModificacion": "2019-11-07T20:38:40.825993Z"
        },
        "FechaCreacion": "2019-11-07T20:38:40.857778Z",
        "FechaModificacion": "2019-11-07T20:38:40.857778Z"
    },
    "Genero": {
        "Id": 33,
        "Nombre": "MASCULINO",
        "CodigoAbreviacion": "MASCULINO",
        "Activo": true,
        "TipoDeDato": "",
        "GrupoInfoComplementariaId": {
            "Id": 6,
            "Nombre": "Genero",
            "Descripcion": "Generos.",
            "CodigoAbreviacion": "Grupo_6",
            "Activo": true,
            "FechaCreacion": "2019-11-25T20:39:54.46085Z",
            "FechaModificacion": "2019-11-25T20:39:54.46085Z"
        },
        "FechaCreacion": "2019-11-25T20:39:54.484077Z",
        "FechaModificacion": "2019-11-25T20:39:54.484077Z"
    },
    "FechaNacimiento": "1994-09-02T05:00:00.000Z",
    "SoporteDocumento": {
        "nombre": "SoporteDocumento",
        "file": {},
        "url": {
            "changingThisBreaksApplicationSecurity": "blob:http://localhost:4200/905b5c76-816f-4eda-9b58-5e18bac5ad06"
        },
        "IdDocumento": 2
    },
    "Foto": {
        "nombre": "Foto",
        "file": {},
        "url": {
            "changingThisBreaksApplicationSecurity": "blob:http://localhost:4200/0749fd35-0c75-422d-88d0-199e221dccda"
        },
        "IdDocumento": 1
    },
    "Usuario": "fdbarretos"
}

**Comment by fabianbarreto02** [comment]
Se de por finalizada la tarea, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se despliega función en el mid y se verifica funcionalidad desde el clliente:
![Captura de pantalla de 2019-12-09 06-34-39](https://user-images.githubusercontent.com/14035745/70432812-22b0ba00-1a4e-11ea-983b-a6c79a0a7ead.png)
