### ISSUE TITLE
Desarrollo API MID de registro proyecto académico en SGA (16 Horas)

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#6]
Se debe desarrollar el api mid para el manejo de transaciones del cliente y el api crud definido en la [issue](https://github.com/udistrital/proyecto_academico_crud/issues/2), este debe cumplir con los siguientes requerimientos:

- [x] El MID debe realizar los registros en API OIKOS y API proyectos_academicos.
- [x] El MID debe cumplir con los lineamientos puestos por OAS.

Lider Técnica : @mafeave

**Comment by fabianbarreto02** [comment]
Se desarrolla el controlador MID en la Rama Proyecto_academico, este realiza el post en el API proyectos_academico_crud y realiza un POST a el Api oikos de solo una dependencia, no crea depenencia padre ni hija, se espera revisión con lider técnica para revisar si cumple con lo pedido.

**Comment by mafeave** [comment]
Se debe realizar reunión con el Core y el grupo de Entregables para establecer cómo hacer el registro de dependencias en OIKOS.

Se da por terminada la tarea.
