### ISSUE TITLE
Pruebas unitarias API MID para consulta_oferta, producción académica, ICFES y eventos

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/sga_mid#7]
Realizar pruebas unitarias dle api mid del Sistema de Gestión Academica.

**Comment by JuanPiedrahita** [comment]
Se recibe link de [documento ](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit)de creación de pruebas unitarias para api crud

**Comment by JuanPiedrahita** [comment]
Se desarrollaron 75 escenarios de prueba, incluyendo el archivo de icfes que tiene uan estructura diferente para el post. Es importante recalcar que estas pruebas estan sujetas a los inserts de las tablas parametricas puesto que al ser un MID depende de otros APIs, por lo cual es importante que cuando se agreguen estos inserts se tengan en cuenta los cambios en las pruebas unitarias puesto que de no ser así estas fallaran, por el momento y para dejar constancia del funcionamiento de las mismas se adjunta captura de pantalla de una ejecución exitosa.

![image](https://user-images.githubusercontent.com/25555966/64928779-68107300-d7e2-11e9-9dd1-6e0c7a2c2696.png)

**Comment by mafeave** [comment]
Se da por finalizada la tarea, completar documento realizado por @fabianbarreto02
