### ISSUE TITLE
Realizar el metodo a nivel Api_MID para realizar el registro de los criterios a varios proyectos cuando lo es necesario - 6 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#70]
Se debe desarrollar una función en el api MID para que realice el registro de los criterios de diferente proyectos académicos cuando lo requieran, la issue debe cumplir con los siguiente requerimientos:

- [x] La función debe recibir la información proveniente del cliente,

- [x] La función debe organizar cada registro para cada proyecto.

- [x] Debe registras los criterios en el api de evaluación inscripción por cada proyecto recibido.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se espera revisión por parte de lider técnica @mafeave

**Comment by mafeave** [comment]
Se verifica función creada en el mid para el registro de los criterios de admisión a 1 y varios proyectos academicos, https://github.com/udistrital/sga_cliente/issues/162

**Comment by mafeave** [comment]
Revisar que cuando se hace el registro a programas que ya tienen registrado el criterio seleccionado, se genera una excepción de violación al constraint unique en evaluacion_inscripcion
![Captura de pantalla de 2020-01-21 19-29-16](https://user-images.githubusercontent.com/14035745/72855179-a3391c00-3c84-11ea-8fcf-818828044d6e.png)

Para este caso se debería primero verificar si la carrera ya tiene el criterio registrado para el periodo y actualizar el registro

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue, se aclara que se gastaron mas horas de las planeadas por ajuste dada por la lider técnica, se espera revisión de @mafeave

**Comment by mafeave** [comment]
Se verifica ajuste de acuerdo a la observación realizada.
