### ISSUE TITLE
Ajustar registro masivo de puntajes del ICFES - 16 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#74]
Se debe realizar el ajuste del controlador que realizar la carga masiva de los icfes por cambios en el modelo de datos, la issue debe cumplir con los siguiente requerimientos:

- [x] Revisar lo desarrollado anteriormente y revisar que funcione.

- [x] Realizar ajustes a las consultas y registros en el api inscripcion_crud con la data proveniente del archivo icfes.

- [x] Realizar el ajuste a la transacción ya establecida por el desarrollo anterior  por cambios en el modelo.

- [x] Realizar el ajuste del registro de las notas de los criterios icfes de forma masiva.

Lider Técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se inicia el proceso de ajuste del controlador

**Comment by fabianbarreto02** [comment]
Se da por finalizada la tarea se espera revision tecnica por parte de @mafeave, tener en cuenta que para ejecutar pruebas se tiene que tener los siguiente prerequisitos:

- Realizar el insert de los datos de pruebas de personas y codigos icfes [insert](https://drive.google.com/drive/folders/1dpOiB80a2TaiQS-4lBQmPLSllbwxX4Wi)

- El archivo icfes de prueba se escoge el siguiente [Archivo](https://drive.google.com/drive/u/0/folders/1PSwD1ViHuBF08vZ_mLsz1SOLvQR0OPbo)

**Comment by mafeave** [comment]
Hacer migración para cambio del tipo de dato del campo activo en la tabla evaluacion_inscripcion.detalle_evaluacion

Tener presente que:
- está quedando quemado el id del periodo académico: https://github.com/udistrital/sga_mid/blob/b5ecfcd9ec115d987e1f6d60f5d46b16151212ca/controllers/archivo_icfes.go#L40
- está quedando quemado el id del tipo inscripción: https://github.com/udistrital/sga_mid/blob/b5ecfcd9ec115d987e1f6d60f5d46b16151212ca/controllers/archivo_icfes.go#L119
