### ISSUE TITLE
Para carga masiva ICFES del módulo de admisiones, se debe incluir el periodo, guardar los puntajes por área, ajuste migrate y eliminar la opción de "Nombre" - 6 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#78]
Se debe realizar los siguientes ajustes a nivel MID API definidos por lider técnica:

- [x] se debe ajustar que el JSON de la tabla detalle_evaluacion para que a parte de registrar la nota por porcentaje se registre el puntaje original de cada subcriterio.

**Comment by fabianbarreto02** [comment]
Se realiza ajuste definido se espera revision por parte de lider técnico

**Comment by mafeave** [comment]
Se verifica el ajuste para que a parte de registrarse la nota por porcentaje se registre el puntaje original de cada subcriterio.

Ejemplo del detalle de la evaluación en el campo detalle_calificacion de la tabla evaluacion_inscripcion.detalle_evaluacion
`{"Puntajes":{"PMA": "67", "PCN": "74", "PLC":"59","PSC": "69", "PIN": "69" },"Notas":{"Area1": "20.099999999999998","Area2": "14.8","Area3": "17.7","Area4": "6.9","Area5": "6.9"}}`
