### ISSUE TITLE
Crear en el MID función para obtener el puntaje total de la inscripción criterio_icfes - 10 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#79]
Se debe crear una función en el mid donde traiga los puntajes finales calculados para los aspirantes a nivel pregrado y que su unico criterio de selección sea el icfes, la issue debe cumplir con los siguientes requerimientos:

- [x] La consulta se debe hacer con el periodo y el programa a consultar.

**Comment by fabianbarreto02** [comment]
Se inicia proceso de desarrollo

**Comment by fabianbarreto02** [comment]
Se realiza el metodo que consulta el puntaje total de un periodo y proyecto particular, se necesita enviar un json asi para la consulta:
`{
"Id_periodo": 1,
  "Id_proyecto": 2
  }`
Ademas de traer toda la información de puntaje total que exista tambien consulta y agrega el nombre completo, tipo de documento y numero de documento para issue futuras.

Se espera revisión técnica

**Comment by mafeave** [comment]
Revisar que en el API de evaluacion_inscripcion **/v1/detalle_evaluacion** retorna `null `y no un json vacio `{}`, por lo que se genera un 404

**Comment by mafeave** [comment]
Se verifica funcionamiento del servicio, se adjunta imagen de la respuesta retornada:
![imagen](https://user-images.githubusercontent.com/14035745/93119532-8f18b380-f687-11ea-8184-841c9b498594.png)

Dado que es una consulta la que se está realizando, se sugiere modificar el método a un **GET** con los parámetros de entrada `id_periodo` y `id_proyecto`
