### ISSUE TITLE
Cambiar el estado de los aspirantes de acuerdo al puntaje y los cupos habilitados por proyecto curricular, función en el MID - 20 horas

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#80]
Se debe realizar una funcion a nivel MID que reciba el id o los id de los proyectos y el id del periodo, esta revisara cuantos cupos estan asignados y cuantos cupos opcionales, después consulta cuantos aspirante existen para ese proyecto organiza de mayor a menor el puntaje total del criterio icfes y realiza el cambio de estado del aspirante si es admitido, opcional o no admitido, la issue debe cumplir con los siguiente requerimientos:

- [x] La funcion debe recibir el periodo y o los proyectos a realizar funcion.

- [x]  Consultar el numero de cupos asignados y opcionales para los proyectos y el periodo.

- [x] Realizar la consulta de los aspirante a los proyectos en el periodo seleccionado.

- [x] Organizar de mayor a menor los aspirante con el puntaje total del criterio icfes.

- [x] Realizar el cambio de estado a cada aspirante a admitido, opcional y no admitido dependiendo a los cupos asignados

**Comment by fabianbarreto02** [comment]
Se da inicio al desarrollo de la issue

**Comment by fabianbarreto02** [comment]
Se realiza el migrations necesario para los cambios de estados necesario para la tarea, estos se pueden observar en el [commit](https://github.com/udistrital/inscripcion_crud/commit/9a2496c4b3b64aa11a31924a5cedb25806ae10d2)

**Comment by fabianbarreto02** [comment]
El metodo revise un JSON de esta forma:

{
    "Proyectos": [
        {
            "Id": 23,
            "Nombre": "INGENIERIA TOPOGRAFICA",
            "TelefonoDependencia": "3239300 4023 - 4024",
            "CorreoElectronico": "ingtopografica@udistrital.edu.co",
            "DependenciaTipoDependencia": [
                {
                    "Id": 17,
                    "TipoDependenciaId": {
                        "Id": 1,
                        "Nombre": "PROYECTO CURRICULAR",
                        "Descripcion": "",
                        "CodigoAbreviacion": "Tipo_1",
                        "Activo": true,
                        "FechaCreacion": "2019-11-05T22:35:39Z",
                        "FechaModificacion": "2019-11-05T22:35:39Z"
                    },
                    "DependenciaId": {
                        "Id": 23,
                        "Nombre": "INGENIERIA TOPOGRAFICA",
                        "TelefonoDependencia": "3239300 4023 - 4024",
                        "CorreoElectronico": "ingtopografica@udistrital.edu.co",
                        "DependenciaTipoDependencia": null
                    },
                    "Activo": true,
                    "FechaCreacion": "2019-11-05T22:37:48Z",
                    "FechaModificacion": "2019-11-05T22:37:48Z"
                },
                {
                    "Id": 335,
                    "TipoDependenciaId": {
                        "Id": 14,
                        "Nombre": "PREGRADO",
                        "Descripcion": "",
                        "CodigoAbreviacion": "Tipo_14",
                        "Activo": true,
                        "FechaCreacion": "2019-11-05T22:35:41Z",
                        "FechaModificacion": "2019-11-05T22:35:41Z"
                    },
                    "DependenciaId": {
                        "Id": 23,
                        "Nombre": "INGENIERIA TOPOGRAFICA",
                        "TelefonoDependencia": "3239300 4023 - 4024",
                        "CorreoElectronico": "ingtopografica@udistrital.edu.co",
                        "DependenciaTipoDependencia": null
                    },
                    "Activo": true,
                    "FechaCreacion": "2019-11-05T22:38:22Z",
                    "FechaModificacion": "2019-11-05T22:38:22Z"
                }
            ]
        },
        {
            "Id": 26,
            "Nombre": "LICENCIATURA EN BIOLOGIA",
            "TelefonoDependencia": "3239300 3010 – 3099 - 3093",
            "CorreoElectronico": "licbiologia@udistrital.edu.co",
            "DependenciaTipoDependencia": [
                {
                    "Id": 20,
                    "TipoDependenciaId": {
                        "Id": 1,
                        "Nombre": "PROYECTO CURRICULAR",
                        "Descripcion": "",
                        "CodigoAbreviacion": "Tipo_1",
                        "Activo": true,
                        "FechaCreacion": "2019-11-05T22:35:39Z",
                        "FechaModificacion": "2019-11-05T22:35:39Z"
                    },
                    "DependenciaId": {
                        "Id": 26,
                        "Nombre": "LICENCIATURA EN BIOLOGIA",
                        "TelefonoDependencia": "3239300 3010 – 3099 - 3093",
                        "CorreoElectronico": "licbiologia@udistrital.edu.co",
                        "DependenciaTipoDependencia": null
                    },
                    "Activo": true,
                    "FechaCreacion": "2019-11-05T22:37:48Z",
                    "FechaModificacion": "2019-11-05T22:37:48Z"
                },
                {
                    "Id": 303,
                    "TipoDependenciaId": {
                        "Id": 14,
                        "Nombre": "PREGRADO",
                        "Descripcion": "",
                        "CodigoAbreviacion": "Tipo_14",
                        "Activo": true,
                        "FechaCreacion": "2019-11-05T22:35:41Z",
                        "FechaModificacion": "2019-11-05T22:35:41Z"
                    },
                    "DependenciaId": {
                        "Id": 26,
                        "Nombre": "LICENCIATURA EN BIOLOGIA",
                        "TelefonoDependencia": "3239300 3010 – 3099 - 3093",
                        "CorreoElectronico": "licbiologia@udistrital.edu.co",
                        "DependenciaTipoDependencia": null
                    },
                    "Activo": true,
                    "FechaCreacion": "2019-11-05T22:38:17Z",
                    "FechaModificacion": "2019-11-05T22:38:17Z"
                }
            ]
        }
    ],
    "Periodo": {
        "Id": 2,
        "Nombre": "2019-3",
        "Ano": "2019",
        "Periodo": "3",
        "Descripcion": "segundo periodo",
        "CodigoAbreviacion": "2019-3",
        "Activo": true,
        "NumeroOrden": 2,
        "TipoPeriodoId": {
            "Id": 1,
            "Nombre": "Periodo académico",
            "Descripcion": "Periodo académico",
            "CodigoAbreviacion": "PA",
            "Activo": true,
            "NumeroOrden": 1,
            "FechaCreacion": "2019-07-10 23:44:54.013628 +0000 UTC",
            "FechaModificacion": "2019-07-10 23:44:54.013628 +0000 UTC"
        },
        "FechaCreacion": "2019-09-03 21:25:12.740113 +0000 UTC",
        "FechaModificacion": "2019-09-03 21:25:12.740113 +0000 UTC"
    }
}

**Comment by fabianbarreto02** [comment]
Se realiza el cambio de estado de cada aspirante sugun su puntaje total de icfes para un unico criterio de evaluación, revisa cantidad de cupos y de acuerdo ha eso actualiza el estado del aspirante en el api de inscripcion_crud, se da por finalizada la issue, se espera revision tecnica.

**Comment by mafeave** [comment]
Se verifica funcionamiento del cambio de estado desde el swagger del API MID, cuerpo de la petición:
`{
	"Proyectos": [{
		"Id": 25
	}],
	"Periodo": {
		"Id": 2
	}
}`

Se verifica funcionamiento con llamada desde el cliente.
