### ISSUE TITLE
Crear función para consultar calendarios para llenar la tabla de consulta

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#92]
Se debe crear una función para ordenar la consulta de calendario para implementación de función a nivel de cliente, la issue debe cumplir los siguientes:

- [x] La función debe recibir un Id para consultar la información  del calendario seleccionado.

- [x] La función debe organizar un objeto (json) con la siguiente información : calendario, proceso relacionados, actvidades relacionadas

- [x] La función debe devolver el objetos con toda la información requerida.

**Comment by ricardoavendano** [comment]
Inicio de tarea

**Comment by ricardoavendano** [comment]
1. Se analiza error en tipo campo CalendarioPadreId de la tabla calendario, se cambia a null,
commit: ac7e8ef1e8cae0165ba03b51f50c9f71164d2f80

2. En compañía del líder técnico @fabianbarreto02 se analiza esta tarea y se llega a la conclusión que se necesita el siguiente consumo del endpoint asi:
http://pruebasapi2.intranetoas.udistrital.edu.co:8107/v2/calendario_evento?query=TipoEventoId__Id.CalendarioID__Id:1

**Comment by fabianbarreto02** [comment]
Se define que no era necesario la creación de una función para consultar las actividades y los proceso de un calendario especifico pues la misma configuración del api ya se podia filtrar esta información, tambien en el proceso de esta tarea se encontro un bug respecto a la consula del api get all en los controladores calendario y calendario_evento y se realizo su respectivo ajuste al bug, se da por finalizada la issue
