### ISSUE TITLE
Revisar si es necesario función para clonar calendario, en mid o solo cliente 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#93]
Se debe analizar si es necesario la creación o no de una función para la función de clonar calendario, si es necesario se debe realizar la creación de la función para este proceso.

**Comment by fabianbarreto02** [comment]
Crear nueva issue para creación de la función

**Comment by fabianbarreto02** [comment]
Prueba

**Comment by fabianbarreto02** [comment]
prueba 2

**Comment by fabianbarreto02** [comment]
prueba 3

**Comment by fabianbarreto02** [comment]
Se debe relacionar la issue donde se esta creando la función

**Comment by ricardoavendano** [comment]
Se realiza la validación, y si es necesario crear la función para clonar calendario, se detalla en el siguiente issue
https://github.com/udistrital/sga_cliente/issues/231

**Comment by fabianbarreto02** [comment]
Se da por terminada la issue
