### ISSUE TITLE
Revisión y ajuste de libreria time bogota en todos los repositorios del sistema 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#94]
Se debe revisar todos apis crud que tienen en comun el sistema de SGA cuentan con las libreria time_bogota, la issue debe cumplir con los siguientes requerimientos:

- [x]  Revisar los repositorios relacionados en el [team](https://github.com/orgs/udistrital/teams/academica/repositories)

- [x] Si se encuentra un repositorio que se encuentre activo sin la libreria de time_bogota realizar los ajustes necesarios

**Comment by jupmorenor** [comment]
Se da inicio con la realización de la tarea

**Comment by jupmorenor** [comment]
Se realiza revisión de los repositorios CRUD de [Académica](https://github.com/orgs/udistrital/teams/academica/repositories) con respecto al uso de la librería **time_bogota**, encontrando lo siguiente:

- [proyecto_academico_crud](https://github.com/udistrital/proyecto_academico_crud): usa _auto_now_ para establecer la fecha.

- [inscripcion_crud](https://github.com/udistrital/inscripcion_crud): usa _auto_now_ para establecer la fecha.

- [produccion_academica_crud](https://github.com/udistrital/produccion_academica_crud): los modelos tienen los campos de fecha pero no se les insertan datos.

- [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud): el modelo detalle_evaluacion.go no actualiza la fecha de modificación en la función update.

- [descuento_academico_crud](https://github.com/udistrital/descuento_academico_crud): aplica la librería en los modelos. 

- [eventos_crud](https://github.com/udistrital/eventos_crud): aplica la librería en los controladores.

**Comment by jupmorenor** [comment]
Se realizan las correcciones necesarias en los repositorios CRUD de [Académica](https://github.com/orgs/udistrital/teams/academica/repositories) y se generan los pull request correspondientes para su aceptación, así:

- [proyecto_academico_crud](https://github.com/udistrital/proyecto_academico_crud/pull/29)

- [inscripcion_crud](https://github.com/udistrital/inscripcion_crud/pull/48)

- [produccion_academica_crud](https://github.com/udistrital/produccion_academica_crud/pull/20)

- [evaluacion_inscripcion_crud](https://github.com/udistrital/evaluacion_inscripcion_crud/pull/28)

- [descuento_academico_crud](https://github.com/udistrital/descuento_academico_crud/pull/10)

**Comment by jupmorenor** [comment]
Con esto se da por finalizada la  tarea.

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de todos los pull requests  y se actualiza la rama de develop, no se despliega en pruebas por auditoria externar
