### ISSUE TITLE
Crear función para buscar calendario academico a un proyecto particular 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#95]
Se debe crear una función de consulta a nivel mid para cargar un calendario academico que cuente con un calendario activo, la issue debe cumplir con los siguientes requerimientos:

- [x] La función debe consular el json en la tabla calendario con el id del proyecto que se consultado.

- [x] La función debe retornar el calendario completo de proyecto que tiene vinculado el calendario

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by jupmorenor** [comment]
Se da preferencia a que la función devuelva el ID del calendario, en lugar de retornar un calendario completo, teniendo en cuenta que esto facilita el flujo de trabajo en el cliente

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
