### ISSUE TITLE
Crear función para consulta de calendarios con ajuste de nombre del periodo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#97]
Se debe realizar una función mid que consulte todos los calendarios registrados y ajuste el campo Id del periodo por el nombre correspondiente, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear la función en el api mid para su consulta

**Comment by jupmorenor** [comment]
Se da inicio con la solución de la tarea

**Comment by jupmorenor** [comment]
Se da por finalizada la tarea

**Comment by fabianbarreto02** [comment]
Se revisa la issue y se despliega en pruebas
