### ISSUE TITLE
Realizar función que permita crear la actividad y posterior post en la tabla calendario_evento_tipo_publico

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/sga_mid#99]
Se debe desarrollar una función que reciba el objeto del cliente con la actividad y los id de los tipos de publico seleccionados para el posterior registro, se debe primero crear el calendaria_evento y con el id  del evento creado se registra en la tabla  calendario_evento_tipo_publico con el id y los tipos de publicos, la issue debe cumplir con las siguientes requerimientos:

- [x] Construir el json desde el cliente con la información necesaria 

- [x] Crear función en el mid que reciba el json y realice el registro de la actividad, reciba el id creado y posterior registras el registro en calendario_evento_tipo_publico con el id y los tipos de publicos seleccionado

**Comment by gabrielablanco** [comment]
Se da inicio con la solución de la tarea

**Comment by gabrielablanco** [comment]
Se implementó la función crear_actividad_calendario la cual agrega las actividades y posteriormente toma el id para añadirlo a la tabla de rompimiento. Se manejaron algunas excepciones por si la función llega a fallar.
